### ISSUE TITLE
op: labels

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#1006]
> For every create function, the descriptor.label is carried over to the object.label.

**Comment by lokokung** [comment]
In https://github.com/gpuweb/gpuweb/pull/2496 the spec for the label was changed to allow `undefined` but was later changed again in https://github.com/gpuweb/gpuweb/commit/b0f1cdf8840633645291951d847b90b15aa18b72. Make sure that these tests reflect the most updated spec for the labels: https://www.w3.org/TR/webgpu/#gpuobjectbase

**Comment by lokokung** [comment]
For the labels, we should also make sure to test behavior defined in https://github.com/gpuweb/gpuweb/pull/3484. Specifically, that if we have multiple `GPUObjectBase` wrappers that refer to the same underlying object, that changing the label on one of the `GPUObjectBase`'s does not change it for the others.

This is most notably easy to test via `GPUPipelineBase.getBindGroupLayout`.

**Comment by greggman** [comment]
I'd like to take ownership of this issue if you haven't started.

**Comment by kainino0x** [comment]
I'm pretty certain Jie hasn't been working on this.
