### ISSUE TITLE
web_platform: reference tests imported to WPT need to be fuzzy

### ISSUE THREAD

**Issue by Juanmihd** [gpuweb/cts#1045]
This is work related to https://bugs.chromium.org/p/chromium/issues/detail?id=1083478

Some of the reference tests that use canvas 2d as reference need some fuzziness to pass.

**Comment by kainino0x** [comment]
Thanks for the fixes! Is this fully resolved now, or might there be more to do to get things fully passing?

**Comment by Juanmihd** [comment]
I'm waiting to validate this with Chrome and the test infrastructure to see that everything passes and then I will close this.

**Comment by kainino0x** [comment]
I think this is fixed now.
