### ISSUE TITLE
copyImageBitmapToTexture tests don't work on Workers

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#112]
These tests use document.createElement which is not available on workers.

In Chrome, we might be able to use `new OffscreenCanvas()` instead, but this requires OffscreenCanvas 2d support, which other browsers may not have.

Perhaps we should do this without a canvas. It should be possible since the "expected" data is already there.

Run with <http://localhost:8080/?worker&q=cts:copyImageBitmapToTexture:>

@shaoboyan , could you take a look? Thanks!

**Comment by shaoboyan** [comment]
@kainino0x  Sry for late replying. Will look into it.

**Comment by shaoboyan** [comment]
It's ok to remove the usage of canvas for current test but I'm afraid that we still need canvas. When we have a path to support texture backed image bitmap, I think the only way to create it is by using canvas. BTW, remove canvas makes we cannot check imageData with alpha value that is 255 can be handled correctly.
WDYT?

**Comment by kainino0x** [comment]
No worries, no rush.

Let's make sure we have at least one test that will work on workers with no canvas at all, and for those that require canvas, use a canvas element if `document` exists; otherwise, check (1) OffscreenCanvas exists and (2) OffscreenCanvas can create a `'2d'` context, and if not just `t.skip('OffscreenCanvas "2d" context not available')`.

**Comment by shaoboyan** [comment]
Got it.

**Comment by kainino0x** [comment]
fixed by #116
