### ISSUE TITLE
Extend the ShaderModuleEntryPoint tests with Unicode

### ISSUE THREAD

**Issue by Kangz** [gpuweb/cts#1130]
Now that WGSL supports unicode, we should extend these tests to check that unicode entrypoints are correctly matched.

**Comment by kainino0x** [comment]
Testing bugs should be tracked in the "CTS" project; I added it (and set the fields)

**Comment by kainino0x** [comment]
(not relevant here, but you can also file new testing requirements as "draft" issues in that tracker up until you need to link to them, like in your PR)

**Comment by lokokung** [comment]
I believe that this is done for compute pipelines. I opened a corresponding draft issue specific to implementing that test called `val: createRenderPipeline,entry_point_name_must_match` so I will close this one for now to keep things clean.

**Comment by lokokung** [comment]
Ah, sorry on double check I see that there is already another issue open for those tests: https://github.com/gpuweb/cts/issues/895

Updated in that issue and removing the duplicate draft.
