### ISSUE TITLE
Change how ULP threshholds are calculated

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#1148]
For a constraint that is described as `c` ULP in the spec, where `c` is a constant value; currently the CTS is implementing a check that the generated values is within `c` ULP steps of the truth value, i.e. the calculated result's binary representation is within `c` bits of the expected value.

Closer reading of the spec indicates that the intended accuracy is actually `c` times one ULP step at the expected value. For the vast majority of cases, these two interpretations are equivalent, except when the expected value is near the boundary in the floating point representation where the difference neighbouring values have different exponents. This means that the tests as written is are more strict than intended.

Vulkan describes their constraints and implements them as `c` * 1ULP, so I am confident that this is the intended reading, since WGSL should have tighter constraints then one of the backend platforms.

**Comment by kainino0x** [comment]
I've added this to the CTS project for tracking, with type "Dependency" since tests will depend on it.
