### ISSUE TITLE
wgsl: literal parsing execution tests

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1192]
Add tests for parsing of literal values. See: https://www.w3.org/TR/WGSL/#literals

**Comment by kainino0x** [comment]
Is this done in #1193? (if so, close it and mark the status in the project as "Completed")

**Comment by dneto0** [comment]
#1193 only tests pass/fail on parsing literals.

We also have to test that the right value is parsed. E.g. that '2i' is the number two.

We have #1472 for checking the values of hex floats.

We also need
- check values of decimal floats,  using the "20 significant digits" rule from https://github.com/gpuweb/gpuweb/pull/3565 
- check values of parsed integers {decimal, hex} x {i, u, or no suffix}
- consider AbstractInt and AbstractFloat not just the concrete types.

**Comment by dneto0** [comment]
There are some excellent underflow-checking cases in https://dawn-review.git.corp.google.com/c/dawn/+/124341

**Comment by dj2** [comment]
I think we can call this complete with the various tests that have been added. If we find there is missing coverage please file followup issues.
