### ISSUE TITLE
wgsl: f32 execution tests for `cosh`

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1202]
Add a f32 execution test for the `cosh` builtin.
```
@const @must_use fn cosh(arg: T) -> T

S is f32
T is S or vecN<S>
```
Returns the hyperbolic cosine of arg, where arg is a hyperbolic [angle](https://www.w3.org/TR/WGSL/#angles) in radians. Approximates the pure mathematical function (e^arg + e^−arg)÷2, but not necessarily computed that way.
[Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector

Accuracy is `Inherited from (exp(x) + exp(-x)) * 0.5`

See https://www.w3.org/TR/WGSL/#cosh-builtin

**Comment by zoddicus** [comment]
f32 is completed, splitting off [f16](https://github.com/gpuweb/cts/issues/2538) and [AbstractFloat](https://github.com/gpuweb/cts/issues/2539) into separate issues
