### ISSUE TITLE
wgsl: f32 execution tests for `exp` builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1204]
Add f32 execution tests for the `exp` builtin.
```
@const @must_use fn exp(e1: T) -> T

S is f32
T is S or vecN<S>
```
Returns the natural exponentiation of e1 (e.g. e^e1). [Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

Accuracy is `3 + 2 * |x| ULP`

See https://www.w3.org/TR/WGSL/#exp-builtin

**Comment by kainino0x** [comment]
Is this done? (if so, close it and mark the status in the project as "Completed")

**Comment by zoddicus** [comment]
It isn't, only f32 has been implemented, AbstractFloat and f16 are still outstanding

**Comment by zoddicus** [comment]
f32 work completed, splitting off [AbstractFloat](https://github.com/gpuweb/cts/issues/2542) & [f16](https://github.com/gpuweb/cts/issues/2543) into separate issues.
