### ISSUE TITLE
wgsl: f32 execution tests for `faceForward` builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1206]
Add f32 execution tests for the `faceForward` builtin.
```
@const @must_use fn faceForward(e1: T,
                                e2: T,
                                e3: T) -> T
T is vecN<f32>
```
Returns e1 if dot(e2, e3) is negative, and -e1 otherwise.

Accuracy is `Inherited from select(-x, x, dot(z, y) < 0.0)`

[See https://www.w3.org/TR/WGSL/#exp2-builtin](https://www.w3.org/TR/WGSL/#faceForward-builtin)

**Comment by zoddicus** [comment]
f32 work is done, splitting [AbstractFloat](https://github.com/gpuweb/cts/issues/2546) and [f16](https://github.com/gpuweb/cts/issues/2547) off into separate issues.
