### ISSUE TITLE
wgsl: f32 execution tests for `fma` builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1207]
Add f32 execution tests for the `fma` builtin.
```
@const @must_use fn fma(e1: T,
                        e2: T,
                        e3: T) -> T
S is f32
T is S or vecN<S>
```
Returns e1 * e2 + e3. [Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

Accuracy is `Inherited from x * y + z`

See https://www.w3.org/TR/WGSL/#fma-builtin

**Comment by zoddicus** [comment]
f32 work completed. Splitting [AbstractFloat](https://github.com/gpuweb/cts/issues/2548) and [f16](https://github.com/gpuweb/cts/issues/2549) into separate issues
