### ISSUE TITLE
wgsl: f32 execution tests for `acos` builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1212]
Add f32 execution tests for the `acos` builtin.
```
@const @must_use fn acos(e: T) -> T

S is f32
T is S or vecN<S>
```
Returns the principal value, in radians, of the inverse cosine (cos^-1) of e.
That is, approximates x with 0 ≤ x ≤ π, such that cos(x) = e.
[Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

Accuracy is
```
The worse of:
     Absolute error 6.77×10-5
     Inherited from atan2(sqrt(1.0 - x * x), x)
```

See https://www.w3.org/TR/WGSL/#acos-builtin

**Comment by dj2** [comment]
See https://github.com/gpuweb/cts/issues/792 for some discussion around accuracy for these tests.

**Comment by zoddicus** [comment]
f32 work completed, splitting [AbstractFloat](https://github.com/gpuweb/cts/issues/2550) and [f16](https://github.com/gpuweb/cts/issues/2551) into separate issues
