### ISSUE TITLE
wgsl: f32 execution tests for `asin` builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1213]
Add f32 execution tests for the `asin` builtin.
```
@const @must_use fn asin(e: T) -> T

S is f32
T is S or vecN<S>
```
Returns the principal value, in radians, of the inverse sine (sin^-1) of e.
That is, approximates x with -π/2 ≤ x ≤ π/2, such that sin(x) = e.
[Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

Accuracy is
```
The worse of:
     Absolute error 6.77×10^-5
     Inherited from atan2(x, sqrt(1.0 - x * x))
```

See https://www.w3.org/TR/WGSL/#asin-builtin

**Comment by dj2** [comment]
See https://github.com/gpuweb/cts/issues/792 for some discussion around accuracy for these tests.

**Comment by zoddicus** [comment]
f32 work completed, splitting [AbstractFloat](https://github.com/gpuweb/cts/issues/2552) and [f16](https://github.com/gpuweb/cts/issues/2553) off into separate issues
