### ISSUE TITLE
wgsl: f32 execution tests for `length` builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1216]
Add f32 execution tests for the `length` builtin.
```
@const @must_use fn length(e: T) -> S

S is f32
T is S or vecN<S>
```
Returns the length of e.
Evaluates to the absolute value of e if T is [scalar](https://www.w3.org/TR/WGSL/#scalar).
Evaluates to sqrt(e[0]2 + e[1]2 + ...) if T is a vector type.

Accuracy is `Inherited from sqrt(dot(x, x)) in the vector case, and sqrt(x*x) in the scalar case.`

See https://www.w3.org/TR/WGSL/#length-builtin

**Comment by zoddicus** [comment]
f32 work completed, splitting [AbstractFloat](https://github.com/gpuweb/cts/issues/2554) and [f16](https://github.com/gpuweb/cts/issues/2555) into separate issues
