### ISSUE TITLE
wgsl: f32 execution tests for `distance` builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1217]
Add f32 execution tests for the `distance` builtin.
```
@const @must_use fn distance(e1: T,
                             e2: T) -> S

S is f32
T is S or vecN<S>
```
Returns the distance between e1 and e2 (e.g. length(e1 - e2)).

Accuracy is `Inherited from length(x - y)`

See https://www.w3.org/TR/WGSL/#distance-builtin

**Comment by zoddicus** [comment]
f32 work completed, splitting [AbstractFloat](https://github.com/gpuweb/cts/issues/2556) and [f16](https://github.com/gpuweb/cts/issues/2557) off into their own issues.
