### ISSUE TITLE
wgsl: f32 execution tests for `acosh` builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1221]
Add f32 execution tests for the `acosh` builtin.
```
@const @must_use fn acosh(e: T) -> T

S is f32
T is S or vecN<S>
```
Returns the inverse hyperbolic cosine (cosh^-1) of e, as a hyperbolic [angle](https://www.w3.org/TR/WGSL/#angles) in radians.
That is, approximates x with 0 ≤ x ≤ ∞, such that cosh(x) = e.
[Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

Accuracy is `Inherited from log(x + sqrt(x * x - 1.0))`

See https://www.w3.org/TR/WGSL/#acosh-builtin

**Comment by zoddicus** [comment]
f32 work completed, splitting [AbstractFloat](https://github.com/gpuweb/cts/issues/2558) and [f16](https://github.com/gpuweb/cts/issues/2559) into separate issues
