### ISSUE TITLE
wgsl: execution test for asinh builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1222]
Add f32 execution tests for the `asinh` builtin.
```
@const @must_use fn asinh(e: T) -> T

S is f32
T is S or vecN<S>
```
Returns the inverse hyperbolic sine (sinh^-1) of e, as a hyperbolic [angle](https://www.w3.org/TR/WGSL/#angles) in radians.
That is, approximates x such that sinh(x) = e.
[Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

Accuracy is `Inherited from log(x + sqrt(x * x + 1.0))`

See https://www.w3.org/TR/WGSL/#asinh-builtin

**Comment by zoddicus** [comment]
f32 work completed, splitting [AbstractFloat](https://github.com/gpuweb/cts/issues/2560) and [f16](https://github.com/gpuweb/cts/issues/2561) into separate issues
