### ISSUE TITLE
wgsl: f32 execution tests for `atanh` builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1223]
Add f32 execution tests for the `atanh` builtin.
```
@const @must_use fn atanh(e: T) -> T

S is f32
T is S or vecN<S>
```
Returns the inverse hyperbolic tangent (tanh^-1) of e, as a hyperbolic [angle](https://www.w3.org/TR/WGSL/#angles) in radians.
That is, approximates x such that tanh(x) = e.
[Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

Accuracy is `Inherited from log( (1.0 + x) / (1.0 - x) ) * 0.5`

See https://www.w3.org/TR/WGSL/#atanh-builtin

**Comment by zoddicus** [comment]
f32 work completed, splitting [AbstractFloat](https://github.com/gpuweb/cts/issues/2562) and [f16](https://github.com/gpuweb/cts/issues/2563) into own issues
