### ISSUE TITLE
wgsl: execution test for degrees builtin function

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1224]
Add an execution test for the `degrees` builtin

```
T is AbstractFloat, f32, f16, vecN<AbstractFloat>, vecN<f32>, or vecN<f16>
 @const fn degrees(e1: T ) -> T

Converts radians to degrees, approximating e1 × 180 ÷ π. Component-wise when T is a vector
```

## Accuracy
```
Inherited from x * 57.295779513082322865
```

See `degrees` in https://www.w3.org/TR/WGSL/#float-builtin-functions

**Comment by kainino0x** [comment]
Is this done? (if so, close it and mark the status in the project as "Completed")

**Comment by zoddicus** [comment]
It isn't, only f32 has been implemented, AbstractFloat and f16 are still outstanding

**Comment by zoddicus** [comment]
f32 work is completed, splitting off [AbstractFloat](https://github.com/gpuweb/cts/issues/2564) and [f16](https://github.com/gpuweb/cts/issues/2565) into their own issues.
