### ISSUE TITLE
wgsl: execution test for modf for scalar f32

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1226]
Add an execution test for the `modf` builtin using scalar f32

```
T is f32

@const fn modf(e:T) -> __modf_result

Splits e into fractional and whole number parts. Returns the __modf_result built-in structure, defined as follows:
struct __modf_result {
  fract : f32, // fractional part
  whole : f32  // whole part
}
```

See `modf` in https://www.w3.org/TR/WGSL/#float-builtin-functions

**Comment by zoddicus** [comment]
This I believe completed. There is some work to handle structure responses in CTS better, but that is independent of this issue
