### ISSUE TITLE
wgsl: f32 execution tests for `normalize` builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1230]
Add f32 execution tests for the `normalize` builtin.
```
@const @must_use fn normalize(e: vecN<T> ) -> vecN<T>

T is f32
```
Returns a unit vector in the same direction as e.

Accuracy is `Inherited from x / length(x)`

See https://www.w3.org/TR/WGSL/#normalize-builtin

**Comment by zoddicus** [comment]
Completed f32 work, moving [AbstractFloat](https://github.com/gpuweb/cts/issues/2570) and [f16](https://github.com/gpuweb/cts/issues/2571) to their own issues
