### ISSUE TITLE
wgsl: f32 execution tests for `radians` builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1232]
Add f32 execution tests for the `radians` builtin.
```
@const @must_use fn radians(e1: T) -> T

S is f32
T is S or vecN<S>
```
Converts degrees to radians, approximating e1 × π ÷ 180. [Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector

Accuracy is `Inherited from x * 0.017453292519943295474`

See https://www.w3.org/TR/WGSL/#radians-builtin

**Comment by kainino0x** [comment]
Is this done in #1676? (if so, close it and mark the status in the project as "Completed")

**Comment by zoddicus** [comment]
f32 work is completed, moving [AbstractFloat](https://github.com/gpuweb/cts/issues/2576) and [f16](https://github.com/gpuweb/cts/issues/2577) into their own issues.
