### ISSUE TITLE
wgsl: execution test for round builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1235]
Add a f32 execution test for the `round` builtin.
```
@const @must_use fn round(e: T) -> T
S is f32
T is S or vecN<S>
```
Result is the integer k nearest to e, as a floating point value.
When e lies halfway between integers k and k + 1, the result is k when k is even, and k + 1 when k is odd.
[Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

Accuracy is `Correctly rounded`

See https://www.w3.org/TR/WGSL/#round-builtin

**Comment by zoddicus** [comment]
Splitting up by FP type, [AbstractFloat](https://github.com/gpuweb/cts/issues/2509) & [f16](https://github.com/gpuweb/cts/issues/2510)
Closing this as covering f32
