### ISSUE TITLE
wgsl: f32 execution tests for `sign` builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1236]
Add f32 execution tests for the `sign` builtin.
```
@const @must_use fn sign(e: T) -> T

S is f32
T is S, or vecN<S>
```
Result is:
1 when e > 0
0 when e = 0
-1 when e < 0
[Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

Accuracy is `Correctly rounded`

See https://www.w3.org/TR/WGSL/#sign-builtin

**Comment by zoddicus** [comment]
f32 and i32 work completed, moving [AbstractFloat](https://github.com/gpuweb/cts/issues/2582), [f16](https://github.com/gpuweb/cts/issues/2583) and [AbstractInt](https://github.com/gpuweb/cts/issues/2584) to their own issues
