### ISSUE TITLE
wgsl: f32 execution test for `sinh` builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1237]
Add a f32 execution test for the `sinh` builtin.
```
@const @must_use fn sinh(e: T) -> T

S is f32
T is S or vecN<S>
```
Returns the hyperbolic sine of e, where e is a hyperbolic [angle](https://www.w3.org/TR/WGSL/#angles) in radians. Approximates the pure mathematical function (e^arg − e^−arg)÷2, but not necessarily computed that way.
[Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

Accuracy is `Inherited from (exp(x) - exp(-x)) * 0.5`

See https://www.w3.org/TR/WGSL/#sinh-builtin

**Comment by zoddicus** [comment]
f32 portion completed, moving [AbstractFloat](https://github.com/gpuweb/cts/issues/2536) and [f16](https://github.com/gpuweb/cts/issues/2535) work to their own issues.
