### ISSUE TITLE
wgsl: f32 execution test for `smoothstep` builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1238]
Add a f32 execution test for the `smoothstep` builtin.
```
@const @must_use fn smoothstep(low: T,
                               high: T,
                               x: T) -> T

S is f32
T is S or vecN<S>
```
Returns the smooth Hermite interpolation between 0 and 1. [Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.
For scalar T, the result is t * t * (3.0 - 2.0 * t), where t = clamp((x - low) / (high - low), 0.0, 1.0).

Accuracy is `Inherited from t * t * (3.0 - 2.0 * t),
where t = clamp((x - low) / (high - low), 0.0, 1.0)`

See https://www.w3.org/TR/WGSL/#smoothstep-builtin

**Comment by zoddicus** [comment]
f32 portion is completed, moving [AbstractFloat](https://github.com/gpuweb/cts/issues/2534) and [f16](https://github.com/gpuweb/cts/issues/2533) work to their own issues.
