### ISSUE TITLE
wgsl: f32 execution test for `sqrt` builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1239]
Add a f32 execution test for the `sqrt` builtin.
```
@const @must_use fn sqrt(e: T) -> T

S is f32
T is S or vecN<S>
```
Returns the square root of e. [Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

Accuracy is `Inherited from 1.0 / inverseSqrt(x)`

See https://www.w3.org/TR/WGSL/#sqrt-builtin

**Comment by zoddicus** [comment]
f32 portion completed, splitting [AbstractFloat](https://github.com/gpuweb/cts/issues/2531) and [f16](https://github.com/gpuweb/cts/issues/2532) into their own issues
