### ISSUE TITLE
wgsl: f32 execution test for `step` builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1240]
Add a f32 execution test for the `step` builtin.
```
@const @must_use fn step(edge: T,
                         x: T) -> T

S is f32
T is S or vecN<S>
```
Returns 1.0 if edge ≤ x, and 0.0 otherwise. [Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

Accuracy is `Correctly rounded`

See https://www.w3.org/TR/WGSL/#step-builtin

**Comment by zoddicus** [comment]
f32 work completed, separating off [AbstractFloat](https://github.com/gpuweb/cts/issues/2530) and [f16](https://github.com/gpuweb/cts/issues/2529) into own issues
