### ISSUE TITLE
wgsl: f32 execution test for `tan` builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1241]
Add a f32 execution test for the `tan` builtin.
```
@const @must_use fn tan(e: T) -> T
S is f32
T is S or vecN<S>
```
Returns the tangent of e, where e is in radians. Component-wise when T is a vector.

Accuracy is `Inherited from sin(x) / cos(x)`

See https://www.w3.org/TR/WGSL/#tan-builtin

**Comment by zoddicus** [comment]
Splitting up by FP type [AbstractFloat](https://github.com/gpuweb/cts/issues/2506) [f16](https://github.com/gpuweb/cts/issues/2507), closing this as covering f32
