### ISSUE TITLE
wgsl : f32 execution test for `tanh` builtin.

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1242]
Add a f32 execution test for the `tanh` builtin.
```
@const @must_use fn tanh(e: T) -> T

S is f32
T is S or vecN<S>
```
Returns the hyperbolic tangent of e, where e is a hyperbolic angle in radians.
Approximates the pure mathematical function (e^arg − e^−arg) ÷ (e^arg + e^−arg) but not necessarily computed that way.
Component-wise when T is a vector.

Accuracy is `Inherited from sinh(x) / cosh(x)`

See https://www.w3.org/TR/WGSL/#tanh-builtin

**Comment by zoddicus** [comment]
f32 work completed, breaking off [AbstractFloat](https://github.com/gpuweb/cts/issues/2528) and [f16](https://github.com/gpuweb/cts/issues/2527) work into separate issues.
