### ISSUE TITLE
wgsl: f32 execution test for `trunc` builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1243]
Add a f32 execution test for the `trunc` builtin.
```
@const @must_use fn trunc(e: T) -> T

T is f32
```
Returns [truncate](https://www.w3.org/TR/WGSL/#truncate)(e), the nearest whole number whose absolute value is less than or equal to the absolute value of e. [Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

Accuracy is `Correctly rounded`

See https://www.w3.org/TR/WGSL/#trunc-builtin

**Comment by zoddicus** [comment]
f32 portion completed, [AbstractFloat](https://github.com/gpuweb/cts/issues/2525) and [f16](https://github.com/gpuweb/cts/issues/2524) are broken off into their own issues.
