### ISSUE TITLE
wgsl: f32 execution test for `determinant` builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1245]
Add a f32 execution test for the `determinant` builtin.
```
@const @must_use fn determinant(e: matCxC<T>) -> T
T is f32
```
Returns the determinant of e.

Accuracy is `Infinite ULP`

See https://www.w3.org/TR/WGSL/#determinant-builtin

**Comment by zoddicus** [comment]
f32 portion is done, [AbstractFloat](https://github.com/gpuweb/cts/issues/2523) and [f16](https://github.com/gpuweb/cts/issues/2522) are broken off into their own issues
