### ISSUE TITLE
wgsl: f32 execution test for `transpose` builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1246]
Add a f32 execution test for the `transpose` builtin.
```
@const @must_use fn transpose(e: matRxC<T>) -> matCxR<T>
T is f32
```
Returns the transpose of e.

Accuracy is `Correctly rounded`

See https://www.w3.org/TR/WGSL/#transpose-builtin

**Comment by zoddicus** [comment]
f32 portion is done, breaking off [AbstractFloat](https://github.com/gpuweb/cts/issues/2521) and [f16](https://github.com/gpuweb/cts/issues/2520) into their own issues.
