### ISSUE TITLE
wgsl: f32 execution test for `dot` builtin

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1247]
Add a f32 execution test for the `dot` builtin.
```
@const @must_use fn dot(e1: vecN<T>,
                        e2: vecN<T>) -> T
T is f32
```
Returns the dot product of e1 and e2.

Accuracy is `Inherited from sum of x[i] * y[i]`

See https://www.w3.org/TR/WGSL/#dot-builtin

**Comment by zoddicus** [comment]
Splitting up by FP type, [AbstractFloat](https://github.com/gpuweb/cts/issues/2512), [f16](https://github.com/gpuweb/cts/issues/2513), [AbstractInt](https://github.com/gpuweb/cts/issues/2514), [u32](https://github.com/gpuweb/cts/issues/2515) & [i32](https://github.com/gpuweb/cts/issues/2516)
Closing this as covering f32
