### ISSUE TITLE
wgsl: f16 built-in execution tests

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1248]
List all f16 related built-in here to track the overall built-in execution tests implementation.

* [x] abs
* [x] acos (#2551)
* [x] acosh (#2559)
* [x] arrayLength
* [x] asin (#2553)
* [x] asinh (#2561)
* [x] atan
* [x] atan2
* [x] atanh (#2563)
* [x] bitcast (#1609)
* [x] ceil
* [x] clamp
* [x] cos
* [x] cosh (#2538)
* [x] cross (#2540)
* [x] degrees (#2565)
* [x] determinant (#2522)
* [x] distance (#2557)
* [x] dot (#2513)
* [x] exp (#2543)
* [x] exp2 (#2544)
* [x] faceForward (#2547)
* [x] floor
* [x] fma (#2549)
* [x] fract
* [x] frexp (#2587)
* [x] inversesqrt
* [x] ldexp
* [x] length (#2555)
* [x] log
* [x] log2
* [x] max
* [x] min
* [x] mix (#2567)
* [x] modf (#2568)
* [x] normalize (#2571)
* [x] pow (#2573)
* [x] radians (#2577)
* [x] reflect (#2579)
* [x] refract (#2580)
* [x] round (#2510)
* [x] saturate
* [x] select
* [x] sign (#2583)
* [x] sin
* [x] sinh (#2535)
* [x] smoothstep (#2533)
* [x] sqrt (#2532)
* [x] step (#2529)
* [x] tan (#2507)
* [x] tanh (#2527)
* [x] transpose (#2520)
* [x] trunc (#2524)

**Comment by jzm-intel** [comment]
Upload this issue to make it a tracker for the whole f16 built-in execution test implementation.

**Comment by zoddicus** [comment]
All subtasks completed. Thanks @jzm-intel for all of the hard work :1st_place_medal:
