### ISSUE TITLE
How to make sure a WGSL test is failing for the right reasons?

### ISSUE THREAD

**Issue by sarahM0** [gpuweb/cts#125]
For example file recursion-fail.wgsl has a recursive function and is a test for validation rule v-0004: Recursion is not allowed. Consider this scenario: A PR implements a syntax change and accidently breaks the recursion detection algorithm. This PR could pass the CTS because test recursion.wgsl could now fail due to using an outdated syntax instead of failing for using recursion.

Possible solutions:

- Encode validation rule numbers in the test names: v-0004-recursion-fail.wgsl 
Implementation:  WGSL has IDs for all validation messages so we can map  v-0004 back to the "recursion is not allowed" validation error in the WGSL spec. A test runner should verify at least one of v-xxxx validation errors matches the prefix of the test file name in this case v-0004.
- Have markers in the test files so that two test cases can be extracted from one test file, a positive and negative test. There would be minimal differences between the two tests.
Implementation: Use markers like #if error/success #endif. The test runners would then be required to process the test file and generate the two test cases.This way both tests fail due to using an outdated syntax construct.

**Comment by sarahM0** [comment]
@Kangz @dj2 @litherum @kvark

**Comment by dj2** [comment]
Thinking about this a bit more, I think we want both.

I want the validation IDs so that we can make sure we have coverage of all the validation errors and we can map them back to our implementations.

I'm realizing I want the markers for non-validation tests. I want to add a set of parser failure cases and knowing that those are failing for a given syntax error would be useful.

**Comment by kainino0x** [comment]
I'm alright with supporting both. FWIW @jdashg and I were the main voices expressing reservations about giving every validation error in the API a unique ID. For that discussion, I think the group semi-settled on optional error IDs, so when an implementation finds that it can't efficiently produce the correct ID, it doesn't have to, but if it does produce an ID, we test that it's the right ID.

**Comment by kainino0x** [comment]
On the topic of where to store the error ID in the test case data, I would kind of prefer not to put it in the filename as it could cause unnecessary churn in the test case list (e.g. if we split an error into two more specific errors, or something).

Here's an alternate idea: put it in a comment at the end of the erroring line in the test shader file. That way we could also test that the implementation has produced the correct line number for the error message. WDYT?

**Comment by sarahM0** [comment]
The mutual agreement is to add the [validation rule number ](webgpu.github.io/gpuweb/wgsl.html#validation) causing the failure as a comment to the beginning of the negative tests.

**Comment by kainino0x** [comment]
Do we think it's feasible to put it on the line with the error, and enforce that in tests?

**Comment by sarahM0** [comment]
> On the topic of where to store the error ID in the test case data, I would kind of prefer not to put it in the filename as it could cause unnecessary churn in the test case list (e.g. if we split an error into two more specific errors, or something).
> 
> Here's an alternate idea: put it in a comment at the end of the erroring line in the test shader file. That way we could also test that the implementation has produced the correct line number for the error message. WDYT?

Commenting the line causing the failure is not possible since in some cases failure is due a non-existing but required item (eg. validation rule v-0019) or caused by a collection of items on different lines.

> Do we think it's feasible to put it on the line with the error, and enforce that in tests?

Commenting the line causing the failure is not possible since in some cases failure is due a non-existing but required item (eg. validation rule v-0019) or caused by a collection of items on different lines.

**Comment by kainino0x** [comment]
Alright, no problem 👍. Maybe we could consider it as an optional check for tests where it does make sense.

**Comment by dj2** [comment]
We no longer have validation IDs in the spec, and we no longer have the `.wgsl` tests directly in the repo. The tests will be re-created as individual tests. Closing this as no longer relevant.
