### ISSUE TITLE
wgsl: Formal parameter of pointer type must be instantiable as a variable

### ISSUE THREAD

**Issue by dneto0** [gpuweb/cts#1395]
See https://github.com/gpuweb/gpuweb/pull/2866 

Disallows things like:

```rust
fn foo(p: ptr<workgroup,array<i32>>) { }
```

**Comment by dj2** [comment]
Done https://github.com/gpuweb/cts/blob/main/src/webgpu/shader/validation/types/pointer.spec.ts
