### ISSUE TITLE
`insertLeaf` not setting `key` correctly.

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1409]
In the `insertLeaf` code we create a `key` (https://github.com/gpuweb/cts/blob/9f4227be09ee268c508e9d5841c4f76772036264/src/common/internal/tree.ts#L530) which is set initialized to blank. The key is then used when inserting into the `parent.children` object.

As far as I can tell, the key is always blank. This causes issues as sometimes the same parent tries to insert two children with the same blank key and triggers they assert about a duplicate key.

**Comment by kainino0x** [comment]
Hm, this is definitely very weird code, but I think it was actually intended. As an example adapted from the comments, I think this is the tree structure you should end up with (keys in [brackets]):

- `suite:a,b:c,d:x=1;*`
    - `['y=2']` -> `suite:a,b:c,d:x=1;y=2;*`
        - `['']` -> `suite:a,b:c,d:x=1;y=2`
        - `['z=3']` -> `suite:a,b:c,d:x=1;y=2;z=3;*`
            - `['']` -> `suite:a,b:c,d:x=1;y=2;z=3`

Do you have an example of how you ended up with duplicate blank keys? I don't think I've ever seen it before.

**Comment by dj2** [comment]
The https://github.com/dj2/gpuweb-cts/tree/builtin_val_01 branch causes the issue. There _is_ a duplicate item in the list which is what seems to be the problem. (`generateTextureTypes` and `subsetOfTypes` both add `texture_2d<i32>`). 

Removing the `texture_2d<i32>` from the `subsetOfTypes` causes the fail with a `''` to go away. But then I get a series of `key '' - fail\nserver error:` messages

**Comment by kainino0x** [comment]
If there's a duplicate, it seems like the error is correct, then? I don't know what's up with the "server error" or where it's coming from, sounds like it might come from Ben's test server, maybe due to too many cases (try subcases?).

BTW, you can dedup values with a nice little trick:
`.combine('type', new Set([...subsetOfTypes(), ...generateTextureTypes()]))`
