### ISSUE TITLE
wgsl: Non UTF-8 text is a valid encoding.

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1429]
Create a CTS test which provides non-utf-8 text to the browser.

**Comment by dj2** [comment]
Requirement from https://www.w3.org/TR/WGSL/#textual-structure

**Comment by mehmetoguzderin** [comment]
Any update here should hopefully keep track of this issue to avoid any conflicting codification as enforcement, since this comes from a horizontal review process: https://github.com/gpuweb/gpuweb/issues/565

**Comment by dj2** [comment]
I believe this is invalid after the spec changes from gpuweb/gpuweb#565. Closing, if this is incorrect, please re-open with comments.
