### ISSUE TITLE
wgsl: Validate various  structs with size/align validate correctly.

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1456]
Create tests with various combinations of `size` and `align` on the struct members to see that things parse correctly.

* [ ] size to odd numbers of bytes and add aligns for various types of elements
* [ ] nested struct with huge odd size
* [ ] `vec3<f32>; f32` or `f32; vec3<f32>` (first could be tucked together in other languages)
* [ ] `mat2x3<f32>` and `mat3x2<f32>`
* [ ] `vec3<f16>`
* [ ] array with element count
* [ ] runtime array
* [ ] array of structs of odd size

**Comment by alan-baker** [comment]
Memory layout tests are here: [memory_layout.spec.ts](https://github.com/gpuweb/cts/blob/main/src/webgpu/shader/execution/memory_layout.spec.ts).
