### ISSUE TITLE
Provide ability to dump WGSL shaders 

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1479]
Currently you need to be integrated into a WebGPU implementation in order to test a WGSL parser. This is fine for the various web engines, but not as useful for other tools.

It would be nice if the CTS had the ability to write the generated shaders to disk so I could run the WGSL tests and store all files to a folder structure somewhere. Each of the tests would be named `foo.pass.wgsl` or `foo.fail.wgsl` if it's a positive or negative test.

**Comment by kainino0x** [comment]
Compile tests should be going through the common `expectCompileResult` method. I think(?) most tests are using it, so we should be able to just add something there to dump shaders and their expected result status.

**Comment by dj2** [comment]
Don't think this is worth pursuing. Closing.

**Comment by ben-clayton** [comment]
For Dawn / Tint folks: `--dump-shaders` will dump shader source with the `./tools/run run-cts` command.
