### ISSUE TITLE
wgsl: validate atomics disallow initializer expressions

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1486]
An atomic can not be initialized, validate that providing an expression for atomic initialization fails.

**Comment by alan-baker** [comment]
This is covered by atomic type validation that check they can only be instantiated in storage and workgroup address spaces and the variable decl validation that checks storage and workgroup cannot have initializers. Atomic type validation also tests that a bunch of expressions are invalid directly on the atomic.
