### ISSUE TITLE
Add missing  RENDER_ATTACHMENT usage when creating multisampled textures

### ISSUE THREAD

**Issue by Jiawei-Shao** [gpuweb/cts#1508]
According to the latest WebGPU SPEC, it is not allowed to create a multisampled texture without RENDER_ATTACHMENT usage, so we need to address this change in the CTS.

**Comment by jzm-intel** [comment]
Shall we have another issue to implement some corresponding CTS test to test the usage validation of RENDER_ATTACHMENT?

**Comment by Jiawei-Shao** [comment]
Hi @jzm-intel,

> Shall we have another issue to implement some corresponding CTS test to test the usage validation of RENDER_ATTACHMENT?

Not yet. I think it's better to land the fix in Dawn first before adding the corresponding CTS test so that the new CTS test won't break the bots. What do you think?

**Comment by kainino0x** [comment]
I've put the spec change https://github.com/gpuweb/gpuweb/pull/2786 in "Needs CTS Issue" to make sure we eventually track it in the CTS tracker. The backlog of items in that state is getting pretty big though. https://github.com/orgs/gpuweb/projects/1#column-6543640
