### ISSUE TITLE
wgsl: Access mode restrictions

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1538]
For both variable declarations ~and pointer~ types:

* [x] Storage address space no address mode (defaults to `read`)
* [x] Storage address space with `read` mode accepted
* [x] Storage address space with `read_write` mode accepted
* [x] Storage address space with `write` mode rejected
* [x] Other address spaces {`function`, `private`, `workgroup`, `uniform`, `storage`}
   * [x] `read`
   * [x] `write`
   * [ ] `read_write` 

[4.5.1 Access Mode Defaults](https://www.w3.org/TR/WGSL/#access-mode-defaults)

Edits:  Testing the pointer type spelling has moved to #2832

**Comment by dneto0** [comment]
Fixed  by #2824
