### ISSUE TITLE
Make timeout deadlines configurable

### ISSUE THREAD

**Issue by austinEng** [gpuweb/cts#1562]
It would helpful to make timeouts configurable so that the times can be scaled/changed when running in different environments.

For example, in some experiments to run tests in parallel using multiple browser instances, it's necessary to scale up timeouts to account for the fact that execution may take longer when the machine is under higher load.

For example, multiple [locations](https://github.com/gpuweb/cts/search?q=raceWithRejectOnTimeout+5000) in the CTS use a hard-coded 5-second timeout.

**Comment by austinEng** [comment]
@kainino0x FYI

**Comment by austinEng** [comment]
Sounds like this feature request may not be particularly important as we're only running up against it for `img.decode()` on Windows NVIDIA. It is likely a Chromium-specific issue where the decode is going wrong when called simultaneously from multiple browser instances.

**Comment by kainino0x** [comment]
All timeouts should bottom out in https://github.com/gpuweb/cts/blob/main/src/common/util/timeout.ts which redirects to WPT's step_timeout when it exists, which itself does scale timeouts for slow devices (and slow tests maybe?). So if we need our own way of controlling that it should be a very targeted change to timeout.ts.

**Comment by austinEng** [comment]
Turns out for Chrome, the hangs were occurring because the `decode()` request isn't sent until the frame is committed. And, when running tests in parallel, browser windows were stacked such that some were completely occluded. Completely occluded windows never resolved the decode promise. We can work around this with a flag that tells Chrome to not background the window even if it's not visible. Can see https://crbug.com/1338339 for more detail.

So, additional features for timeouts aren't needed, and in any case, based on @kainino0x's above comment, the facilities to scale timeouts should already exist if the browser's test harness provides its own definition of `step_timeout`.
