### ISSUE TITLE
Set up automatic deploy for gh-pages branch

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#16]

**Comment by kainino0x** [comment]
@beaufortfrancois, would you be able to help me out with this?

**Comment by beaufortfrancois** [comment]
Of course. How do you envision this?
Would having content of `out/` generated folder in a new `gh-pages` branch would be enough or you looking for more?

**Comment by kainino0x** [comment]
Yup, just out/ and the out-wpt/ directory too even though that won't be directly useful on the GitHub Pages site.

**Comment by beaufortfrancois** [comment]
@kainino0x I've decided to go with a light Travis CI solution as you can see at https://github.com/gpuweb/cts/compare/cb7e03d7ddf8d5d3b3c35b67d09d6a6c4ade31fc..0fb3fbda08a785781fe05130c31eb39dbe0ddcc5

The branch `gh-pages` is basically the result of `yarn test` with additional `out` and `out-wpt` folders.

WebGPU page is available at https://gpuweb.github.io/cts and updated automatically when a PR gets merged in `master` branch and when `master` branch is updated.

I've updated Github description as well.

![image](https://user-images.githubusercontent.com/634478/62466591-f29c9600-b791-11e9-9e6e-7e9ca9549e19.png)

FYI @Kangz

**Comment by beaufortfrancois** [comment]
CTS works great in Chrome Canary and Safari Tech Preview for macOS. Thank you @kainino0x!

![image](https://user-images.githubusercontent.com/634478/62466853-a4d45d80-b792-11e9-88b7-198b4208e2f4.png)
