### ISSUE TITLE
wgsl: execution test, bitcast: f16 cases remain

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1609]
* [x] Identity `bitcast` for i32, u32
* [x] Identity `bitcast` for f32
* [x] Identity `bitcast` for f16
* [x] `bitcast<u32>(i32)`
* [x] `bitcast<u32>(f32)`
* [x] `bitcast<i32>(u32)`
* [x] `bitcast<i32>(f32)`
* [x] `bitcast<f32>(u32)`
* [x] `bitcast<f32>(i32)`
* [x] `bitcast<vecN<u32>>(vecN<i32>)`
* [x] `bitcast<vecN<u32>>(vecN<f32>)`
* [x] `bitcast<vecN<i32>>(vecN<u32>)`
* [x] `bitcast<vecN<i32>>(vecN<f32>)`
* [x] `bitcast<vecN<f32>>(vecN<u32>)`
* [x] `bitcast<vecN<f32>>(vecN<i32>)`
* [x] `bitcast<u32>(vec2<f16>)`
* [x] `bitcast<i32>(vec2<f16>)`
* [x] `bitcast<f32>(vec2<f16>)`
* [x] `bitcast<vec2<f16>>(u32)`
* [x] `bitcast<vec2<f16>>(i32)`
* [x] `bitcast<vec2<f16>>(f32)`
* [x] `bitcast<vec2<u32>>(vec4<f16>)`
* [x] `bitcast<vec2<i32>>(vec4<f16>)`
* [x] `bitcast<vec2<f32>>(vec4<f16>)`
* [x] `bitcast<vec4<f16>>(vec2<u32>)`
* [x] `bitcast<vec4<f16>>(vec2<i32>)`
* [x] `bitcast<vec4<f16>>(vec2<f32>)`

Validation tests inplemented in `shader\validation\expression\call\builtin\bitcast.spec.ts`:

* [x] `bitcast` to/from `mat` types fail
* [x] `bitcast` to/from `vec3<f16>` fail
* [x] `bitcast` to/from `f16` fails
* [x] `bitcast` to non-numeric types fails
* [x] const `bitcast` from integer types to inf and nan values fail

**Comment by dneto0** [comment]
#2754 tests failure of:
- to/from mat
- to/from non-numeric types
- const bitcast resulting in to inf nan floats

**Comment by dneto0** [comment]
The remaining tests require f16 support.

**Comment by jzm-intel** [comment]
All tasks are done with f16 execution tests landed with PR #2897, closing this issue.
