### ISSUE TITLE
wgsl: Validate logical expressions

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1623]
# Not
- [x] `!` on a `true` -> `false`
- [x] `!` on a `false` -> `true`
- [x] `!` on a `vec` goes component-wise
- [x] `!` on a non-bool fails parse e.g `!1`

# Short-circuiting 
* [x] `||` where first is true, second isn't evaluated (`a++` in second slot)
* [x] `&&` where first is false, second isn't evaluated (`a++` in second slot)
* [x] `||` where both false is false
* [x] `&&` where both true is true
* [ ] `||` with a non-bool on the LHS or RHS fails to validate
* [ ] `&&` with a non-bool on the LHS or RHS fails to validate

# Logical
* [x] `|` evaluates both LHS and RHS
* [x] `&` evaluates both LHS and RHS
* [x] `|` with a vector gives component-wise combination
* [x] `&` with a vector gives component-wise combination
* [x] `|` with a non-bool LHS or RHS fails to validate
* [x] `&` with a non-bool LHS or RHS fails to validate

- https://www.w3.org/TR/WGSL/#logical-expr

**Comment by amaiorano** [comment]
Some of this is already done, see: https://github.com/gpuweb/cts/pull/1870

**Comment by dj2** [comment]
Looks like this is done. Please file followups for anything missing.
