### ISSUE TITLE
wgsl: Comparison expression tests

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1627]
* [ ] `==`
* [ ] `!=`
* [ ] `<`
* [ ] `>`
* [ ] `<=`
* [ ] `>=

For
+ [ ] AbstractInt
+ [x] AbstractFloat
+ [x] #2406
+ [x] f16, 
+ [x] #2404
+ [x] For vectors (component wise)

- https://www.w3.org/TR/WGSL/#comparison-expr

**Comment by dneto0** [comment]
#2405 covers the vector cases for i32, u32

**Comment by dneto0** [comment]
The f32 comparison tests already existed, but were in binary/f32_logical.spec.ts

**Comment by zoddicus** [comment]
Ticking `for vectors` because all of the current tests run with .vectorize.
