### ISSUE TITLE
val: Test copyExternalImageToTexture with dimensions

### ISSUE THREAD

**Issue by Gyuyoung** [gpuweb/cts#1694]
When a texture is used as a destination parameter of copyExternalImageToTexture, texture.[dimension](https://gpuweb.github.io/gpuweb/#dom-gputexture-dimension) must be ["2d"](https://gpuweb.github.io/gpuweb/#dom-gputexturedimension-2d).

**Comment by kainino0x** [comment]
Closing because it was marked complete, which I think is accurate.
