### ISSUE TITLE
wgsl: validate `enable`

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1708]
* [ ] `enable f16;`
* [ ] declaration before enable fails
* [ ] `staticAssert` before enable fails
* [ ] `/* comment\n\n*/\n\nenable f16`;
* [ ] `enable(f16);` fails
* [ ] `enable\n\nf16/*comment*/;`
* [ ] `enable f16; enable 16;`

- https://www.w3.org/TR/WGSL/#enable-directive-section

**Comment by dneto0** [comment]
Enable can take a list of extensions.
They can be redundant, so  

`enable f16, f16;` should be allowed
