### ISSUE TITLE
wgsl: enforce that declared array element count is element_count_expression

### ISSUE THREAD

**Issue by dneto0** [gpuweb/cts#1731]
Example Tint bug: https://bugs.chromium.org/p/tint/issues/detail?id=1630 

Element_count_expression is either additive_expression or bitwise_expression.

Example, this is valid:

```
@group(0) @binding(0) var<storage,read_write> b: array<u32, 2+2>;

@compute @workgroup_size(1)
fn foo() {
  b[3] = 1;
}
```

But I get this error from Tint:
```
a.wgsl:1:62 error: expected '>' for array declaration
@group(0) @binding(0) var<storage,read_write> b: array<u32, 2+2>;
                                                             ^
```

**Comment by dj2** [comment]
The array tests cover this now. https://github.com/gpuweb/cts/blob/main/src/webgpu/shader/validation/types/array.spec.ts
