### ISSUE TITLE
Track all the buffers and textures with TrackForCleanup()

### ISSUE THREAD

**Issue by Jiawei-Shao** [gpuweb/cts#1752]
We should track all the buffers and textures with TrackForCleanup() in the test body so that they can be safely destroyed after the completion of the tests. Otherwise these resources may be destroyed at a random moment by GC, which will cause some flaky test failures due to the bugs in buffer.destroy() or texture.destroy().

**Comment by kainino0x** [comment]
@Jiawei-Shao What are the bugs in buffer.destroy() and texture.destroy(), can you link to them?

**Comment by Jiawei-Shao** [comment]
The related issue reports are [dawn:1628](https://bugs.chromium.org/p/dawn/issues/detail?id=1628) and [chromium:1237175](https://bugs.chromium.org/p/chromium/issues/detail?id=1237175).
