### ISSUE TITLE
wgsl: `ldexp` tests might now be incorrectly failing SwiftShader

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#1791]
I have recently been fixing up some of the logic in the fullF32Range and fullI32Range functions, so that they generate correct/interesting values. This has uncovered cases for `ldexp` where SwiftShader is now being failed that I think maybe incorrect.

Specifically:
  - EXPECTATION FAILED: (-1.1754942106924411e-38 (0x807fffff subnormal), 1 (0x00000001))
        returned: -2.3509885615147286e-38
        expected: [-2.3509884213848822e-38,0]
...

This smells like a off by 1ULP issue, i.e. something is getting rounded early/late. I will have to investigate what Vulkan CTS is doing, etc.

**Comment by zoddicus** [comment]
Lots of discussion internally with @dneto0 about this.
This is likely actually a bug in SwiftShader's implementation and a missing areas of coverage in Vulkan CTS.
So the test as-is is correct.

That being said, given that Vulkan CTS has been approving drivers with missing coverage in this corner case, WebGPU may need a spec change to say something like "if input is subnormal and result is normal then ldexp isn't defined" to deal with real world devices.

**Comment by dneto0** [comment]
Swiftshader bug is: https://b.corp.google.com/issues/243791551https://b.corp.google.com/issues/243791551

**Comment by dneto0** [comment]
I'd like to
- clarify WGSL to better explain what's intended
- avoid loosening the spec for now, with expectation that SwiftShader will be fixed.  
- wait for further experience with more WebGPU targets

**Comment by zoddicus** [comment]
Looks like the SwiftShader change has landed and propagated, and the spec has been updated.
