### ISSUE TITLE
wgsl: shader-creation and pipeline-creation errors for invalid expressions

### ISSUE THREAD

**Issue by dneto0** [gpuweb/cts#1814]
From https://github.com/gpuweb/gpuweb/issues/3253

* out of bounds indexing on arrays, vectors, matrices:  https://github.com/gpuweb/gpuweb/pull/3400
* integer division by zero
* floating point domain errors

**Comment by dj2** [comment]
I believe these are all covered by various validation tests now. If anything is missing, please open specific issues.
