### ISSUE TITLE
webgpu:api,validation,queue,writeBuffer:ranges: tries to `writeBuffer` with Float16Array

### ISSUE THREAD

**Issue by austinEng** [gpuweb/cts#1832]
This is not valid since `Float16Array`, added in #1828, is not a real JS TypedArray type.

It fails with 
```
THREW TypeError, instead of OperationError: TypeError: Failed to execute 'writeBuffer' on 'GPUQueue': Overload resolution failed.
      at (elided: below max severity)

  - EXCEPTION: Failed to execute 'writeBuffer' on 'GPUQueue': Overload resolution failed.
    TypeError: Failed to execute 'writeBuffer' on 'GPUQueue': Overload resolution failed.
        at runTest (http://127.0.0.1:44467/third_party/webgpu-cts/src/webgpu/api/validation/queue/writeBuffer.spec.js:68:19)
        at RunCaseSpecific.fn (http://127.0.0.1:44467/third_party/webgpu-cts/src/webgpu/api/validation/queue/writeBuffer.spec.js:112:9)
```

**Comment by zoddicus** [comment]
Yeah, I can see that now.
I am going to see if I can come up with a small fix that converts things through F32Array internally, so that we are not trying to write out f16 buffers... though that will be a major bodge that will need to be addressed when we implement proper f16 tests, or if I just need to revert all of this and try again.

**Comment by austinEng** [comment]
I think we can also just skip the Float16Array case in the writeBuffer tests - could be good enough

**Comment by zoddicus** [comment]
I am not particularly familiar with how writeBuffer is used, so I don't know if it is safe to skip in the test, or if that is just going to lay down traps for us to hit in the future. I have written up a fix that looks like it works https://github.com/gpuweb/cts/pull/1833

**Comment by kainino0x** [comment]
IIRC the goal of these writeBuffer tests is just to make sure that the range arguments work correctly with all of the possible overloads (ArrayBuffer and all the typed arrays). Float16Array isn't one so it doesn't need to be tested.
