### ISSUE TITLE
Tracking issue for overrides NaN/Inf value validation

### ISSUE THREAD

**Issue by shrekshao** [gpuweb/cts#1838]
on going spec pull request: https://github.com/gpuweb/gpuweb/issues/3435

CTS test: https://github.com/gpuweb/cts/pull/1830

Making sure it's not dropping on the floor

**Comment by kainino0x** [comment]
This will cause a TypeError because WebIDL doesn't allow it. https://webidl.spec.whatwg.org/#idl-double
