### ISSUE TITLE
wgsl: execution tests for Logical Expressions

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#1868]
[Five](https://www.w3.org/TR/WGSL/#logical-expr) boolean operations are defined in the spec that should be tested
- [x] `!e`
- [x] `e1 || e2`
- [x] `e1 && e2`
- [x] `e1 | e2`
- [x] `e1 & e2`

The short circuiting behaviour of `&&` and `||` are already tested in src/webgpu/shader/execution/evaluation_order.spec.ts

**Comment by dj2** [comment]
See also #1623 for the validation side of this.

**Comment by zoddicus** [comment]
Thanks, apparently my search skills in GitHub are lacking since I didn't find that bug when looking for existing issues

**Comment by zoddicus** [comment]
Also added tests to confirm non-short circuiting behaviour.
