### ISSUE TITLE
wgsl:  indexing X by non-const-expr index requires X to be concrete

### ISSUE THREAD

**Issue by dneto0** [gpuweb/cts#1893]
From https://github.com/gpuweb/gpuweb/pull/3497

Example:

const const_i = 0;
override override_i=0;

fn foo {
  // overflow when converting to concrete result at the let initializer
  // level. Produces shader-creation error
  let x = (vec2(1,1)[const_i]) << vec2(60,60); 

  // like vec2(60%32,60%32);
  let y = (vec2(1,1)[override_i]) << vec2(60,60);  

}

**Comment by dj2** [comment]
I believe this is covered by the https://github.com/gpuweb/cts/blob/main/src/webgpu/shader/validation/expression/access tests.
