### ISSUE TITLE
val: setBindGroup required for a bind group layout that exists but is empty

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#1903]
This would be something like this Dawn test:
https://dawn-review.googlesource.com/c/dawn/+/104820/2/src/dawn/tests/unittests/validation/BindGroupValidationTests.cpp

We probably have similar tests already, for the encoder bind groups validation:
https://gpuweb.github.io/gpuweb/#abstract-opdef-validate-encoder-bind-groups
but we should make sure we have this particular test.

**Comment by kainino0x** [comment]
@Gyuyoung maybe you want to take this since you've been working on #1891

**Comment by Gyuyoung** [comment]
@kainino0x ok, let me take a look at this soon!

**Comment by Gyuyoung** [comment]
I think I've fixed this issue through https://github.com/gpuweb/cts/pull/1910 and https://github.com/gpuweb/cts/pull/1919. So I mark this issue as 'complete'.
