### ISSUE TITLE
Add validation tests on effective buffer binding size

### ISSUE THREAD

**Issue by Jiawei-Shao** [gpuweb/cts#1905]
We need to add validation tests on effective buffer binding size.  According to the latest WebGPU SPEC, the effective buffer binding size must be a multiple of 4 if the binding type is storage or read-only storage.

EDIT: spec issue: https://github.com/gpuweb/gpuweb/pull/3477

**Comment by kainino0x** [comment]
Thanks for filing this. For testing issues please:
- Add it to the project tracker and set fields appropriately
- If associated with a spec change, link it and remove the "needs-cts-issue" from that issue

I've done both for this issue.

**Comment by Jiawei-Shao** [comment]
Got it. Thanks! @kainino0x
