### ISSUE TITLE
Need to filter infinity/nan out of test cases when running with a const inputSource

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1978]
The `inf` and `nan` values are not valid when doing a const-eval (can't be written in WGSL and generation is an error). For test cases like `pack2x16float` we use the `sparseF32Range` which includes Infinity. This causes the test to error with a validation error.

Need a way to filter out the infinity value when using the various range generation functions.

**Comment by zoddicus** [comment]
This has been completed. I don't have the PR offhand, but I believe it was done by @amaiorano
