### ISSUE TITLE
Different device Queue and Fence tests send validation error to the wrong receiver

### ISSUE THREAD

**Issue by austinEng** [gpuweb/cts#201]
In the following tests:

webgpu:api,validation,fences:signal_a_fence_on_a_different_device_than_it_was_created_on_is_invalid:
webgpu:api,validation,fences:signal_a_fence_on_a_different_device_does_not_update_fence_signaled_value:

A fence is signaled on a queue from a different device than the fence. The test expects a validation error on the fence's device. This is wrong, and the error should be sent to the "receiver" object, the queue.

**Comment by austinEng** [comment]
Funny. I thought these get auto-closed.

**Comment by kainino0x** [comment]
Seems like it should have, not sure why it didn't.

**Comment by austinEng** [comment]
Maybe it only works if you merge to `master` or the "main" branch. I guess that would make sense.
