### ISSUE TITLE
Support reading structs as outputs from builtin tests

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#2028]
Currently the testing framework only support reading out Scalars and Vectors, but some builtins, i.e. `modf`, return structured data. The current workaround, https://github.com/gpuweb/cts/pull/2014, is to have a test for each member of the output structure that only pulls that member out for testing. This means for a structure with N members there needs to be N almost identical tests being run.

The better solution is for the framework to support something like a  TypeStruct similar to TypeVector that handle packing and unpack out of the buffers, so all the members can be tested in a single invocation. This will probably get tricky to get right.

**Comment by zoddicus** [comment]
Sending to @ben-clayton, since he mentioned he might take a pass at implementing this. Feel free to send back to me.

**Comment by zoddicus** [comment]
For supporting AbstractFloats, I am running into really wanting to be able to return something like a TypeStruct (of 2 u32s). Everything I can think to make this work without just eating the frog on this issue is just hacking workarounds in to the code base.

Given that there are multiple existing tests that could be improved by adding a TypeStruct, and AbstractFloat tests are basically predicated on them, I think it is time to invest the effort. Additionally, I have already added in TypeMatrix, so I am pretty familiar with how to add new types to the framework.

**Comment by dj2** [comment]
This was handled in other ways, the full general solution wasn't necessary.
