### ISSUE TITLE
Should overlapping vertex attributes be allowed?

### ISSUE THREAD

**Issue by austinEng** [gpuweb/cts#204]
Currently `api,validation,vertex_state:check_two_attributes_overlapping` fails on Chrome Canary and perhaps other implementations because the test expects that overlapping vertex attributes are a validation error.

I couldn't find detail about this in the WebGPU spec, and I think it should be allowed. I suggest we reverse the test to check that overlapping attributes **are** allowed.

I tested this in Dawn: a test case with overlapping vertex attributes does indeed pass successfully. It's even allowed to have mixed types aliasing the same data (not sure the use case but it can be done).

**Comment by austinEng** [comment]
@kainino0x

**Comment by kainino0x** [comment]
I don't know what the answer is supposed to be. I don't know if anyone has done the investigation to find out what's allowed by the native APIs. There a number of other edge cases where I'm not sure whether they should be supported or not: https://hackmd.io/@kainino0x/SkYBF7OLL

**Comment by kainino0x** [comment]
If this passes on all the backends with backend validation that would be a pretty strong indicator we should allow it.

**Comment by austinEng** [comment]
It does pass on all backends with backend validation, but I haven't done significant looking into the documentation.

**Comment by kainino0x** [comment]
I think we should go ahead and update the test for now then.

**Comment by austinEng** [comment]
@kainino0x I think you said today the validation layers actually raise an error about this?

**Comment by kainino0x** [comment]
I didn't actually look closely at the validation errors, I had misread them. They're actually just about going out of bounds on an index buffer.

```
ERR: Warning: Validation Error: [ VUID-vkCmdDrawIndexed-indexSize-00463 ] Object 0: handle = 0x40000000004, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0xd4f2594c | vkCmdDrawIndexed() index size (4) * (firstIndex (1) + indexCount (6)) + binding offset (0) = an ending offset of 28 bytes, which is greater than the index buffer size (24). The Vulkan spec states: (indexSize {times} (firstIndex + indexCount) + offset) must be less than or equal to the size of the bound index buffer, with indexSize being based on the type specified by indexType, where the index buffer, indexType, and offset are specified via vkCmdBindIndexBuffer (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdDrawIndexed-indexSize-00463)\n
```

```
ERR: [7256:3600:0814/151022.128:ERROR:gpu_device.cc(96)] GPUDevice: ID3D12CommandList::DrawIndexedInstanced: Current index buffer of Size 24 bytes and Format (0x2a, R32_UINT) is too small for the index count of 6 starting at offset 1 (213)\r\n
ERR: \r\n
ERR:     at CheckDebugLayerAndGenerateErrors (../../third_party/dawn/src/dawn_native/d3d12/DeviceD3D12.cpp:559)\r\n
ERR:     at TickImpl (../../third_party/dawn/src/dawn_native/d3d12/DeviceD3D12.cpp:234)\r\n
ERR: CONSOLE WARNING: ID3D12CommandList::DrawIndexedInstanced: Current index buffer of Size 24 bytes and Format (0x2a, R32_UINT) is too small for the index count of 6 starting at offset 1 (213)\n
```
