### ISSUE TITLE
wgsl: Add basic flow control tests

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/cts#2312]
Add control flow tests:

- [x] `if` statements
  - [x] `else` blocks
  - [x] `else if` blocks
- [x] `switch` statements
- [x] `for` loops
  - [x] initializer statement
  - [x] condition expression
  - [x] continuing statement
  - [x]  `break` statements
  - [x] `continue` statements
- [x] `while` loops
  - [x]  `break` statements
  - [x] `continue` statements
- [x] `loop`s
  - [x]  `break` statements
  - [x] `continue` statements
  - [x] `continuing` blocks
- [x] function calls
  - [x] caller / callee execution order
  - [x] argument evaluation order
- [x] `return` statements
- [x] #2391
- [x] Expression evaluation order (left to right)
- [x] Assignment statement evaluation order

**Comment by dj2** [comment]
This is a more focused version of various other bugs (other bugs are both validation and execution). We should either update the other bugs to remove these execution tests, or make sure we update those bugs as this gets completed.

* `for` statements: https://github.com/gpuweb/cts/issues/1669
* `loop` statements: https://github.com/gpuweb/cts/issues/1666
* `if` statements: https://github.com/gpuweb/cts/issues/1647
* `switch` statements: https://github.com/gpuweb/cts/issues/1648
* function call parameter ordering: https://github.com/gpuweb/cts/issues/1688
* function calls: https://github.com/gpuweb/cts/issues/1687
*

**Comment by ben-clayton** [comment]
I didn't think the `validate` issues covered execution tests like these?

**Comment by dj2** [comment]
I, apparently, didn't use the term `validate` consistently. If you look at those bugs, some of them have an `execution` section (or just items mentioning execution).

So, I think having this uber issue is a good idea, we should just either edit those other bugs, or check off the checkmarks as this bug gets completed.

**Comment by ben-clayton** [comment]
Considering done.
