### ISSUE TITLE
val: Check GPUBuffer.mapState when mapped for read.

### ISSUE THREAD

**Issue by Kangz** [gpuweb/cts#2359]
Chromium code coverage says this isn't tested, only when mapped for write.

**Comment by Kangz** [comment]
Likely covered by #2124 as well?

**Comment by takahirox** [comment]
Likely I was missing read map + mapState case.

> Likely covered by https://github.com/gpuweb/cts/issues/2124 as well?

Yes, I think we can merge this issue with it.

**Comment by kainino0x** [comment]
Merged into #2124
