### ISSUE TITLE
depth_clip_clamp test is not actually testing unclippedDepth?

### ISSUE THREAD

**Issue by dneto0** [gpuweb/cts#2460]
See https://github.com/gpuweb/cts/pull/1030#discussion_r817986746 

The current source is here:

https://github.com/gpuweb/cts/blob/f7a15a8d41d9403049c3e5bf58d5eda2eaefb454/src/webgpu/api/operation/rendering/depth_clip_clamp.spec.ts#L176 

The GPUPrimitiveState being constructed here has a stray undefined or bool value, where you want a key-value pair of `unclippedDepth: undefined` or `unclippedDepth: true` or `unclippedDepth: false`.
Unless I'm misunderstanding TypeScript/JavaScript language constructs?

**Comment by kainino0x** [comment]
If I understand the concern correctly, the code is correct. In JS `{ x }` is short for `{ x: x }` (set the object member `x` to the value of the local variable of the same name `x`).

**Comment by dneto0** [comment]
Well, I better learn JS.  Thanks!
