### ISSUE TITLE
add vec2(), vec3(), vec4()

### ISSUE THREAD

**Issue by dneto0** [gpuweb/cts#2481]
https://github.com/gpuweb/gpuweb/pull/4033

vec2() is the same as vec2(0,0)
vec3() is vec3(0,0,0)
vec4() is vec4(0,0,0,0)

**Comment by alan-baker** [comment]
Some coverage exists in `src/webgpu/shader/validation/expression/call/builtin/value_constructors.spec.ts`. The zero value is tested for const evaluation. Those tests don't include runtime testing though.
