### ISSUE TITLE
Clarify the meaning of the castable constants in constants.ts

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#2501]
Specifically f64_not_castable and last_f64_castable.

This may just require a comment/name change, but how they are calculated should be examined to confirm it is correct.

**Comment by zoddicus** [comment]
@shrekshao It looks like you introduced the first_f64_not_castable and last_f64_castable constants, https://github.com/gpuweb/cts/blob/main/src/webgpu/util/constants.ts#L424

In a recent review I was asked about these, and honestly wasn't 100% sure about them. Can you confirm my understanding from above, or correct it?

I want to either put a comment in the code or change the name of them to be more obvious to me what they are.

**Comment by kainino0x** [comment]
It's not about integers, but about finite values.
`first_f64_not_castable` is the smallest value which, when cast to the type in question (f32 in that link), will produce infinity, per the rounding rules of WebIDL. This generates a TypeError here: https://gpuweb.github.io/gpuweb/#abstract-opdef-to-wgsl-type
`last_f64_castable` is the largest value which will _not_ cast to infinity, instead giving FLT_MAX.

**Comment by kainino0x** [comment]
Also I noticed a typo, this:
```
      first_f64_not_castable: hexToF16(kBit.f16.positive.max) / 2 + 2 ** 16, // mid point of 2**16 and largest f16
```
should say either
```
      first_f64_not_castable: hexToF16(kBit.f16.positive.max) / 2 + 2 ** 15, // mid point of 2**16 and largest f16
```
or
```
      first_f64_not_castable: hexToF16(kBit.f16.positive.max) / 2 + 2 ** 16, // mid point of 2**17 and largest f16
```
(I don't remember which)

**Comment by shrekshao** [comment]
Thanks for Kai's explanation. I found the original thread discussing it: https://github.com/gpuweb/cts/pull/2061#discussion_r1043847123

**Comment by zoddicus** [comment]
Thanks for info, I will update the comments/code
