### ISSUE TITLE
wgsl: f16 execution test for `round` builtin

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#2510]
Add a f16 execution test for the `round` builtin.
```
@const @must_use fn round(e: T) -> T
S is f16
T is S or vecN<S>
```
Result is the integer k nearest to e, as a floating point value.
When e lies halfway between integers k and k + 1, the result is k when k is even, and k + 1 when k is odd.
[Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

Accuracy is `Correctly rounded`

See https://www.w3.org/TR/WGSL/#round-builtin

**Comment by jzm-intel** [comment]
Done in #2762.
