### ISSUE TITLE
val: Make maxBindingsPerBindGroup 1000

### ISSUE THREAD

**Issue by takahirox** [gpuweb/cts#2517]
To follow the recent WebGPU spec update

https://github.com/gpuweb/gpuweb/pull/4050

**Comment by kainino0x** [comment]
Thanks for filing this, I've removed the "needs-cts-issue" label from that gpuweb PR now that an issue is filed. (In the future you should be able to do this as well)

**Comment by takahirox** [comment]
> Thanks for filing this, I've removed the "needs-cts-issue" label from that gpuweb PR now that an issue is filed. (In the future you should be able to do this as well)

Thanks, I was missing that label there. I will do it next time.
