### ISSUE TITLE
wgsl: f16 execution test for `determinant` builtin

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#2522]
Add a f16 execution test for the `determinant` builtin.
```
@const @must_use fn determinant(e: matCxC<T>) -> T
T is f16
```
Returns the determinant of e.

Accuracy is `Infinite ULP`

See https://www.w3.org/TR/WGSL/#determinant-builtin

**Comment by jzm-intel** [comment]
Done via #3013.
