### ISSUE TITLE
wgsl : f16 execution test for `tanh` builtin.

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#2527]
Add a f16 execution test for the `tanh` builtin.
```
@const @must_use fn tanh(e: T) -> T

S is f16
T is S or vecN<S>
```
Returns the hyperbolic tangent of e, where e is a hyperbolic angle in radians.
Approximates the pure mathematical function (e^arg − e^−arg) ÷ (e^arg + e^−arg) but not necessarily computed that way.
Component-wise when T is a vector.

Accuracy is `Inherited from sinh(x) / cosh(x)`

See https://www.w3.org/TR/WGSL/#tanh-builtin

**Comment by jzm-intel** [comment]
Done via #3012.
