### ISSUE TITLE
wgsl: f16 execution test for `smoothstep` builtin

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#2533]
Add a f16 execution test for the `smoothstep` builtin.
```
@const @must_use fn smoothstep(low: T,
                               high: T,
                               x: T) -> T

S is f16
T is S or vecN<S>
```
Returns the smooth Hermite interpolation between 0 and 1. [Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.
For scalar T, the result is t * t * (3.0 - 2.0 * t), where t = clamp((x - low) / (high - low), 0.0, 1.0).

Accuracy is `Inherited from t * t * (3.0 - 2.0 * t),
where t = clamp((x - low) / (high - low), 0.0, 1.0)`

See https://www.w3.org/TR/WGSL/#smoothstep-builtin

**Comment by jzm-intel** [comment]
Done via #2989
