### ISSUE TITLE
wgsl: f16 execution tests for `exp` builtin

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#2543]
Add f16 execution tests for the `exp` builtin.
```
@const @must_use fn exp(e1: T) -> T

S is f16
T is S or vecN<S>
```
Returns the natural exponentiation of e1 (e.g. e^e1). [Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

Accuracy is `1 + 2 * |x| ULP`

See https://www.w3.org/TR/WGSL/#exp-builtin

**Comment by jzm-intel** [comment]
Done with #2963
