### ISSUE TITLE
wgsl: f16 execution tests for `exp2` builtin

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#2544]
Add f16 execution tests for the `exp2` builtin.
```
@const @must_use fn exp2(e1: T) -> T

S is f16
T is S or vecN<S>
```
Returns 2 raised to the power e (e.g. 2^e1). [Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

Accuracy is `1 + 2 * |x| ULP`

See https://www.w3.org/TR/WGSL/#exp2-builtin

**Comment by jzm-intel** [comment]
Done with #2963
