### ISSUE TITLE
wgsl: f16 execution tests for `faceForward` builtin

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#2547]
Add f16 execution tests for the `faceForward` builtin.
```
@const @must_use fn faceForward(e1: T,
                                e2: T,
                                e3: T) -> T
T is vecN<f16>
```
Returns e1 if dot(e2, e3) is negative, and -e1 otherwise.

Accuracy is `Inherited from select(-x, x, dot(z, y) < 0.0)`

[See https://www.w3.org/TR/WGSL/#exp2-builtin](https://www.w3.org/TR/WGSL/#faceForward-builtin)

**Comment by jzm-intel** [comment]
Done via #3015.
