### ISSUE TITLE
wgsl: f16 execution tests for `fma` builtin

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#2549]
Add f16 execution tests for the `fma` builtin.
```
@const @must_use fn fma(e1: T,
                        e2: T,
                        e3: T) -> T
S is f16
T is S or vecN<S>
```
Returns e1 * e2 + e3. [Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

Accuracy is `Inherited from x * y + z`

See https://www.w3.org/TR/WGSL/#fma-builtin

**Comment by jzm-intel** [comment]
Done via #2990
