### ISSUE TITLE
wgsl: f16 execution tests for `acos` builtin

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#2551]
Add f16 execution tests for the `acos` builtin.
```
@const @must_use fn acos(e: T) -> T

S is f16
T is S or vecN<S>
```
Returns the principal value, in radians, of the inverse cosine (cos^-1) of e.
That is, approximates x with 0 ≤ x ≤ π, such that cos(x) = e.
[Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

Accuracy is
```
The worse of:
     Absolute error 3.91×10^-3
     Inherited from atan2(sqrt(1.0 - x * x), x)
```

See https://www.w3.org/TR/WGSL/#acos-builtin

**Comment by jzm-intel** [comment]
Execution test for f16 `acos` is implemented in #2869.
