### ISSUE TITLE
wgsl: f16 execution tests for `asin` builtin

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#2553]
Add f16 execution tests for the `asin` builtin.
```
@const @must_use fn asin(e: T) -> T

S is f16
T is S or vecN<S>
```
Returns the principal value, in radians, of the inverse sine (sin^-1) of e.
That is, approximates x with -π/2 ≤ x ≤ π/2, such that sin(x) = e.
[Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

Accuracy is
```
The worse of:
     Absolute error 3.91×10^-3
     Inherited from atan2(x, sqrt(1.0 - x * x))
```

See https://www.w3.org/TR/WGSL/#asin-builtin

**Comment by jzm-intel** [comment]
Execution test for f16 `asin` is implemented in #2869.
