### ISSUE TITLE
wgsl: f16 execution tests for `mix` builtin

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#2567]
Add f16 execution tests for the `mix` builtin.
```
@const @must_use fn mix(e1: T,
                        e2: T,
                        e3: T) -> T

S is f16
T is S or vecN<S>
```
Returns the linear blend of e1 and e2 (e.g. e1 * (1 - e3) + e2 * e3). [Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

Accuracy is `Inherited from x * (1.0 - z) + y * z`

See https://www.w3.org/TR/WGSL/#mix-builtin

**Comment by jzm-intel** [comment]
Done via #2992
