### ISSUE TITLE
wgsl: f16 execution tests for `normalize` builtin

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#2571]
Add f16 execution tests for the `normalize` builtin.
```
@const @must_use fn normalize(e: vecN<T> ) -> vecN<T>

T is f16
```
Returns a unit vector in the same direction as e.

Accuracy is `Inherited from x / length(x)`

See https://www.w3.org/TR/WGSL/#normalize-builtin

**Comment by jzm-intel** [comment]
Done via #2985
