### ISSUE TITLE
wgsl: f16 execution tests for `pow` builtin

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#2573]
Add f16 execution tests for the `pow` builtin.
```
@const @must_use fn pow(e1: T,
                        e2: T) -> T

S is f16
T is S or vecN<S>
```
Returns e1 raised to the power e2. [Component-wise](https://www.w3.org/TR/WGSL/#component-wise) when T is a vector.

Accuracy is `Inherited from exp2(y * log2(x))`

See https://www.w3.org/TR/WGSL/#pow-builtin

**Comment by jzm-intel** [comment]
Done via #2986
