### ISSUE TITLE
wgsl: f16 execution tests for `reflect` builtin

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#2579]
Add f16 execution tests for the `reflect` builtin.
```
@const @must_use fn reflect(e1: T,
                            e2: T) -> T

T is vecN<f16>
```
For the incident vector e1 and surface orientation e2, returns the reflection direction e1 - 2 * dot(e2, e1) * e2.

Accuracy is `Inherited from x - 2.0 * dot(x, y) * y`

See https://www.w3.org/TR/WGSL/#reflect-builtin

**Comment by jzm-intel** [comment]
Done via #3014.
