### ISSUE TITLE
cts not working at gpuweb.github.io/cts/

### ISSUE THREAD

**Issue by greggman** [gpuweb/cts#2612]
gets error:

> standalone.ts:648 Uncaught (in promise) TypeError: Failed to resolve module specifier "fs". Relative references must start with either "/", "./", or "../".

**Comment by greggman** [comment]
it appears to be this PR

https://github.com/gpuweb/cts/pull/2608

**Comment by kainino0x** [comment]
You're right, that must be it. That happens when the listing.ts files don't get overwritten by gen_listings. I put the steps in the wrong order.
