### ISSUE TITLE
wgsl: f32 validation tests for `sin`

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#2733]
Need coverage that when abs(x) > π, it is rejected for const-eval (shader creation error) and override (pipeline creation error).

**Comment by ben-clayton** [comment]
I'm not sure I understand the task description here. It's not an error to call `sin(x)` with `x` outside of `-π .. π`.
Please can you clarify?

**Comment by dneto0** [comment]
Typo?  asin(x) is not valid outside of [-1, 1].   ?

**Comment by zoddicus** [comment]
During runtime execution, an indeterminate result is returned, but for compile time execution (const-eval and override) this should be a validation error.

I was in the process of clarifying this in the FP primer. https://github.com/gpuweb/cts/pull/2794

**Comment by ben-clayton** [comment]
> During runtime execution, an indeterminate result is returned, but for compile time execution (const-eval and override) this should be a validation error.

I'm not sure that's correct. See:

https://github.com/gpuweb/cts/issues/2730
https://github.com/gpuweb/gpuweb/pull/4220

Basically - we can't guarantee the internal implementation algorithm, nor the order of evaluation, not even the intermediate precision. We only guarantee that the end result of the operation has a specified accuracy. Your interval calculations in the execution tests correctly check the accuracy, but we can't write tests for intermediate values, as we don't specify the internal implementation.

**Comment by ben-clayton** [comment]
To add:

> During runtime execution, an indeterminate result is returned, but for compile time execution (const-eval and override) this should be a validation error.

I don't see anything in the spec that says that where you have an indeterminate runtime eval result, equates to a validation error for const-eval or override-eval.

Rejecting shaders that happen to const eval `sin` or `cos` with values outside of `±π` would certainly break a lot of shaders.
