### ISSUE TITLE
Relaxed precision for copy tests?

### ISSUE THREAD

**Issue by austinEng** [gpuweb/cts#2793]
Some drivers/implementations may implement copies by doing a blit which loses precision. Should the CTS allow a tolerance in checking the results of copies?

For example, the following tests fail on Android Qualcomm GPUs
- webgpu:api,operation,command_buffer,image_copy:offsets_and_sizes:initMethod="WriteTexture";checkMethod="PartialCopyT2B";format="r16float";dimension="1d"
- webgpu:api,operation,command_buffer,image_copy:offsets_and_sizes:initMethod="WriteTexture";checkMethod="PartialCopyT2B";format="r16float";dimension="2d"
- webgpu:api,operation,command_buffer,image_copy:offsets_and_sizes:initMethod="WriteTexture";checkMethod="PartialCopyT2B";format="r16float";dimension="3d"

```
EXPECTATION FAILED: subcase: offsetInBlocks=242;dataPaddingInBytes=0;copyDepth=1
    Array had unexpected contents at indices 486 through 487.
     Starting at index 485:
       actual == 0x: 5b 00 7e 04
       failed ->        xx xx   
     expected ==     5b 9c 7d 04
```

0x5b00 vs 0x5b9c is 224.0 vs. 243.5
0x7e04 and 0x7d04 are both NaN encodings.

**Comment by kainino0x** [comment]
In the case of 224 vs 243.5 I'm surprised. A blit with a format conversion can round, but if there's no format conversion then I wouldn't expect error to be introduced during a blit. If it's implemented with a shader that must mean their intermediate shader representation is lower precision than the data that's going in and out.

Still, we don't have much choice, so yeah, I guess we should allow a tolerance.

For both NaN and subnormals, this would mean we can't guarantee them to be preserved at all.

**Comment by greggman** [comment]
I think this is done. Closing. Re-open if it's not
