### ISSUE TITLE
WGSL test parameters are incompatible with CTS harness

### ISSUE THREAD

**Issue by greggman** [gpuweb/cts#2860]
A bunch of new tests are incompatible with the test harness.

Example:

Go here: [https://gpuweb.github.io/cts/standalone/?q=webgpu:shader,validation,expression,call,builtin,abs:values:stage=%22constant%22;*](https://gpuweb.github.io/cts/standalone/?q=webgpu:shader,validation,expression,call,builtin,abs:values:stage=%22constant%22;*)

Click the `[out]` icon of a test (the icon to the right of the ▶ icon)

For example the first test leads here: [https://gpuweb.github.io/cts/standalone/?q=webgpu:shader,validation,expression,call,builtin,abs:values:stage=%22constant%22;type={%22kind%22:%22abstract-float%22,%22_size%22:8};value=-1.7976931348623157e%2B308](https://gpuweb.github.io/cts/standalone/?q=webgpu:shader,validation,expression,call,builtin,abs:values:stage=%22constant%22;type={%22kind%22:%22abstract-float%22,%22_size%22:8};value=-1.7976931348623157e%2B308)

Which gets an error

> Error: Query `webgpu:shader,validation,expression,call,builtin,abs:values:stage="constant";type={"kind":"abstract-float","_size":8};value=-1.7976931348623157e%2B308` does not match any cases

The issue is the test is parameterized with classes. For example that test effectively does this

```
  params(u =>
    ...
    u.combine('type', [ ScalarType, ...])
    ...
```

But `ScalarType` can't be serialized so when the harness tries to match the query `type={"kind":"abstract-float","_size":8}` it fails because it expects that they're the same type of object but one is `Object` and the other `ScalarType`. Further, if I remove the check for them being the same type of object it expects all of the properties to match but the query only has `kind` and `_size` where as `ScalarType` has also has `read` which is a function

**Comment by dneto0** [comment]
Oof.  Nice catch.
It would be nice if something would have caught this during paramaterization itself.

**Comment by zoddicus** [comment]
Ugh, so this is the whole not being able to JSON-ify thing again (I think). I don't think adding a bunch of logic to json_param_value.ts for scalar and vector types is the appropriate thing to do.

Instead of arrays of objects, the types should be stored in maps with string keys, and the keys can be used for the 
 test params. I believe there is already functionality to automate combine by key instead of whole entry.

**Comment by zoddicus** [comment]
oh, it is just use `keysOf(foo)`, and then index into the map. That should be fine.

**Comment by greggman** [comment]
> It would be nice if something would have caught this during paramaterization itself.

Yea, that would be nice. The tests will need to be fixed before adding the parameter catching test.

**Comment by zoddicus** [comment]
For my own reference, the failing tests are in:
     src/webgpu/shader/validation/expression/call/builtin/abs.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/acos.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/acosh.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/asin.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/asinh.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/atan.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/atan2.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/atanh.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/ceil.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/clamp.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/cos.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/cosh.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/degrees.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/exp.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/exp2.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/inverseSqrt.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/length.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/log.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/log2.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/modf.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/radians.spec.ts     
     src/webgpu/shader/validation/expression/call/builtin/round.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/saturate.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/sign.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/sin.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/sinh.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/sqrt.spec.ts
     src/webgpu/shader/validation/expression/call/builtin/tan.spec.ts

**Comment by greggman** [comment]
I'm going to write the parameter checker and I'll post it here

**Comment by ben-clayton** [comment]
That's fun. I wonder why this works with dawn/node and not the web interface?

**Comment by greggman** [comment]
It probably doesn't work in dawn node

The tests run if you start from a parent with no bad params. It's only if you try to run an individual test or a parent with a bad param, so you have to pass the bad params in the query that it fails.

That includes the CTS runner in chrome since it passes every test case query, one a time.
