### ISSUE TITLE
Add a pseudo-random number generator to CTS

### ISSUE THREAD

**Issue by alan-baker** [gpuweb/cts#2881]
It would be useful to have a pseudo-random number generator for CTS. It could be used for generating deterministic random testcases (e.g. CFGs).  Math.random is insufficient because it can't be seeded at runtime and thus differs compile-to-compile. However, the core function of Math.random is a useful base for the PRNG, generate a random number in the range [0, 1).

**Comment by zoddicus** [comment]
I will take a crack at implementing Mersenne Twister (https://en.wikipedia.org/wiki/Mersenne_Twister) in TS for this, because a) I have implemented MT previously for other non-TS projects so I am familiar with it, b) I don't want to pull in another dependency just for this.
