### ISSUE TITLE
Unable to specify timing metadata for some tests due to 'run:generate-wpt-cts-html-chunked2sec' failing

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#2944]
These tests:
```
webgpu:compat,api,validation,encoding,programmable,pipeline_bind_group_compat:twoDifferentTextureViews,render_pass,used:*
  webgpu:web_platform,copyToTexture,ImageBitmap:from_ImageData:*
  webgpu:web_platform,copyToTexture,ImageBitmap:from_canvas:*
```
currently have the default value of 0 mS specified for them in src/webgpu/listing_meta.json, which causes a warning.

Attempting to update any of them to correct estimates will cause 'run:generate-wpt-cts-html-chunked2sec' to fail with the following error:
```
Error: Generated test variant would produce too-long -actual.txt filename. Possible solutions:
- Reduce the length of the parts of the test query
- Reduce the parameterization of the test
- Make the test function faster and regenerate the listing_meta entry
- Reduce the specificity of test expectations (if you're using them)
```

I have poked at this a little, and I am unclear if this is an issue with the tests taking too long, having too long of names, or something else going wrong in the chunking.

Since the original issue is a warning I am going to leave them as-is, and let Kai, or someone else more familiar with this portion of the testing infra look into this.

**Comment by kainino0x** [comment]
I intentionally left these warnings because I didn't want to go fixing tests in the PR that added all this machinery.

This got fixed by https://github.com/gpuweb/cts/pull/3023
