### ISSUE TITLE
Fix CTS roll into Chromium

### ISSUE THREAD

**Issue by amaiorano** [gpuweb/cts#3028]
See https://github.com/gpuweb/cts/compare/main...amaiorano:cts:fix-cts-roll?expand=1

**Comment by jzm-intel** [comment]
Oops...

**Comment by dneto0** [comment]
I definitely want to add back the testing for negative zeros.  I believe I put some in myself.
We'll have to fix whatever infra is broken by using negative zeros.  In fact I find it amusing and ironic; this issue motivates *why* we should test negative zero in the first place. :-)

**Comment by jzm-intel** [comment]
The issue is caused by test cases query didn't distinguish +/-0.0, and thus return multiple test cases with a precise query.
