### ISSUE TITLE
Lazy-load test cases on /standalone/ page

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#304]
The big nested DOM tree on the /standalone/ runner page needs to lazily load subtrees instead of just loading everything at once. The only level that really needs to be lazily loaded is the "case" subtrees; it should be okay to greedily load everything up to the "test" (g.test()) because every "test" is handwritten, while the list of cases is generated by the ParamsBuilder so it has huge explosions of cases. In other words, the subtrees underneath DOM nodes corresponding to TestQueryLevel 1 and 2 should be greedily loaded, but 3 and 4 should be lazily loaded.

The slightly tricky part is in what it means to "lazily load" those subtrees. The way the actual test loading works there's currently no way to lazily load the underlying data (the TestTree object). However I'm pretty sure that's not very slow right now, so hopefully we can keep that for now, and all that actually needs to be lazy is the creation of the DOM elements which occurs in makeSubtreeHTML (makeSubtreeChildrenHTML).

**Comment by austinEng** [comment]
Might be easiest to just use a frontend library which handles DOM element creation much much better instead of manually doing this. Last I checked the standalone runner isn't checked into WPT so maybe it's okay to have a separate build step for it on Github CI or load a framework from network.

**Comment by kainino0x** [comment]
Right, I forgot to mention that. I was thinking of rewriting the page with some kind of frontend library or data-driven DOM thing. But I didn't know what to use (to generate a DOM tree from a data tree) and I haven't used any of them. Would probably be better overall, though standalone is surprisingly not too gross.
