### ISSUE TITLE
Consider "subcases"

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#305]
Right now we have `.params()` which generates "cases" from a "test" (runs the "test function" once for each case).

Each test case gets a unique identifier and shows up individually in test results (in /standalone/, cmdline, wpt, and the JSON result format). However sometimes this isn't really necessary - it's not important which case is failing unless you're actually digging deeply into it. For example, cases that just differ in buffer ranges.

Consider renaming `.params()` to `.cases()`, and adding a `.subcases()`\* (e.g. `g.test('...').desc('...').cases([...]).subcases(p => [...])`), which is basically like a `for (...) { t.debug(subcase_params); fn(subcase_params); }`. The result of the case would be the combined result of all of the subcases.

Ideally, it would still be possible to manually drill down into a subcase by specifying the subcase params (as printed by `t.debug()`), for developers fixing a bug in an implementation.

**\*Note:** .subcases() needs to be able to receive the parameterization from .cases() because sometimes it might want to depend on it (similar to `.expand()`).

**Comment by kainino0x** [comment]
Likely an important use-case for this is parameterizations over hardware capabilities (e.g. having a test parameterized over all of the allowed sample counts, not just 1 and 4). In order to do this we would need to pass adapter capabilities into subcase creation.

**Comment by kainino0x** [comment]
On the subcase "drill down" feature: https://github.com/gpuweb/cts/pull/444#issuecomment-767967546

> I don't think it's super critical. It's really only for a browser developer testing changes in their browser, and they should have a local copy of the cts anyway where they can just cut down the .subcases() list manually.

**Comment by Kangz** [comment]
Isn't the subcase feature done?

**Comment by kainino0x** [comment]
I kept this open for the "drill down" into subcases but at this point I don't think we need to add it. I think it would be pretty easy to add since Austin already implemented the meat of it for WPT but we're more likely to do a different rework to subcases.
