### ISSUE TITLE
support read-only, read-write storage textures

### ISSUE THREAD

**Issue by dneto0** [gpuweb/cts#3078]
https://github.com/gpuweb/gpuweb/pull/4326 has landed

It's a core feature, except that 'bgra8unorm' read-write and read-only support is guarded by GPUFeature [bgra8unorm-storage](https://gpuweb.github.io/gpuweb/#bgra8unorm-storage)

**Comment by greggman** [comment]
related? https://github.com/gpuweb/cts/issues/2271

**Comment by dneto0** [comment]
> related? #2271

Yes.  :-)  Also #1272
