### ISSUE TITLE
Enforce TS's `readonly` more strictly

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#3126]
The current configuration that we have for linting, etc does not always strictly enforce not assigning to `readonly` params. I have a WIP branch where I know I am improperly assigning to a `readonly`.

I do not get errors about this in my IDE, `npm run fix` or when running the unittests, but `npm run check` and running the CTS via dawn.node it errors on this.

There is probably somewhere in the configs that this is being suppressed or not turned on.

I need to take some time to figure out how make sure this properly enabled and fix up any violates that have snuck in.

**Comment by kainino0x** [comment]
Via this comment
https://gist.github.com/dilame/32709f16e3f8d4d64b596f5b19d812e1?permalink_comment_id=4708061#gistcomment-4708061
I just found this reference for a "strictest" mode for tsconfig:
https://github.com/tsconfig/bases/blob/main/bases/strictest.json
We're already using most of these (except a few I intentionally disabled), I don't suspect any of the remaining ones can make readonly stricter.

It's more likely we can find new linter plugins to enable. There are some suggestions on the TypeScript bug thread, e.g.:
https://github.com/microsoft/TypeScript/issues/18770#issuecomment-532970732

**Comment by zoddicus** [comment]
I don't think I have run into this specific issue in a while, so I am going to close this.

**Comment by kainino0x** [comment]
Oh, I forgot we had this open. I'd actually like to keep this open, as this hole could still let some bugs bypass the safety checks in #3097.

**Comment by kainino0x** [comment]
Linking from https://crbug.com/331393770, will assign myself if I manage to get to this.

**Comment by kainino0x** [comment]
Looked into this a bit. While some of the rules in https://github.com/eslint-functional/eslint-plugin-functional might be helpful, there aren't any that would actually enforce readonly the way we need.

The most useful rules in there are around preferring readonly types, but we only would want to apply that to globals and I don't think there's a way to do this.

I think this is infeasible for now unfortunately.
