### ISSUE TITLE
image_copy.spec.ts makes compat incompatible texture views

### ISSUE THREAD

**Issue by greggman** [gpuweb/cts#3143]
Should we skip the tests in compat or change them to have compat compatible texture views

For example, the code makes a `size: [3, 4, 5]` texture. It then makes views of `arrayLayerCount: 1, baseArrayLayer: 3, dimension: '2d'` view. This fails in compat because the default `textureBindingViewDimension` is `2d-array`

To fix the test requires change it to

* set `textureBindingViewDimension` as appropriate (probably)
* change the shaders so that when `depthOrArrayLayers > 1` the shaders use `texture_2d_array` and pass in `baseArrayLayer` and `arrayLayerCount` as uniforms

We could make the 2 changes above happen in compat only.

**Comment by greggman** [comment]
@kainino0x @SenorBlanco @shrekshao

**Comment by greggman** [comment]
Where the incompatible view is created (might be more than one )

    at ImageCopyTest.initializeDepthAspectWithRendering (:8081/out/webgpu/api/operation/command_buffer/image_copy.spec.js:1203:37)
    at ImageCopyTest.DoCopyTextureToBufferWithDepthAspectTest (:8081/out/webgpu/api/operation/command_buffer/image_copy.spec.js:1270:10)

**Comment by kainino0x** [comment]
SGTM. Probably should do it only in compat to keep any coverage we're getting from those cases, but not necessary if you think that's not useful coverage to keep.
