### ISSUE TITLE
wgsl: test scalar value constructors from abstracts

### ISSUE THREAD

**Issue by dneto0** [gpuweb/cts#3254]
https://github.com/gpuweb/gpuweb/pull/4449

- i32 - avoids conversion to f32 first.
     - This requires preservation of 31 mantissa bits. See below.
- f32 - allows 0xffffffff to f32; it won't overflow
- f16 - allows 0xffffffff to f16; but that will overflow.  The max f16 value is https://float.exposed/0x7bff  65504
- u32 - avoids conversion to f32 first
      - This requires preservation of 32 mantissa bits. See below.

Example code:

```

const big0 = 0x40000000.0;
const big1 = 0x40000001.0;
const big2 = 0x40000002.0;  // these differ only in the 31st bit.
// For the i32 cases:
const_assert( i32(big0) < i32(big1));  // true
const_assert( i32(big1) < i32(big2));  // true

// For u32 cases:
const_assert(  u32( 2.0*big0 ) <  u32( 2.0*big0 + 1.0) ); // true.  etc.
```

**Comment by alan-baker** [comment]
@zoddicus, looking at the related PRs the only potentially missing case is f32. Do you know if f32 from abstract inputs is covered?

**Comment by zoddicus** [comment]
Looking at the source code, looks like they are missing, I will send up a patch adding them in.
