### ISSUE TITLE
Constant evaluation shader test expectations do not allow for rounding as specified in the specification?

### ISSUE THREAD

**Issue by mwyrzykowski** [gpuweb/cts#3261]
Hi, we noticed some failures in https://gpuweb.github.io/cts/standalone/?q=webgpu:shader,execution,expression,call,builtin,cross:abstract_float:inputSource=%22const%22 because were computing results in intermediates instead of performing a store for the constant cross product function.

Specifically the test failed because we generated `0x401fffffffffffff` (7.999999999999999) for an AbstractFloat calculation instead of `0x401ffffffffffffe` (7.999999999999998) which is expected by the test.

We narrowed the difference down to a calculation we were computing the first element of the vec3 cross product as:
```
result.elements[0] = static_cast<T>(u1 * v2 - u2 * v1);
```
which results in `0x401fffffffffffff` on arm64 likely due to the `fnmsub` being generated. However if we instead make three separate stores:
```
auto i1 = u1 * v2;
auto i2 = u2 * v1;
result.elements[0] = static_cast<T>(i1 - i2);
```
we get `0x401ffffffffffffe` as expected by the test. But `0x401fffffffffffff` should also be accepted, since the result is not precisely `0x401ffffffffffffe` and could be rounded up, right?

Based on the wording in https://www.w3.org/TR/WGSL/#const-expr and https://www.w3.org/TR/WGSL/#abstract-float-accuracy, it seems like either result would be valid.

Should the test expectation be changed to accept either result?

For instance with this constant cross product:
```
cross(vec3(1.0, -2.225073858507201e-308, 2.0), vec3(-1.0, -2.0, -1.7976931348623157e+308))
```
in the above code, the values for u1, u2, v1, v2 are as follows:
```
u1 = -2.225073858507201e-308
u2 = 2.0
v1 = -2.0
v2 = -1.7976931348623157e+308
```

We can test this on any arm64 device with clang like so:
```
#include <iostream>
using namespace std;

int main()
{
    auto u1 = -2.225073858507201e-308;
    auto u2 = 2.0;
    auto v1 = -2.0;
    auto v2 = -1.7976931348623157e+308;
    double result = u1 * v2 - u2 * v1;
    double result3 = u1 * v2;
    double result4 = u2 * v1;
    double result2 = result3 - result4;
    cout << std::hexfloat << result << std::endl;
    cout << std::hexfloat << result2 << std::endl;

    return 0;
}
```
and then compiling with clang we see:
% clang++ main.cpp -o cross -std=c++17 && ./cross               
```
0x1.fffffffffffffp+2
0x1.ffffffffffffep+2
```
based on how the result it rounded, it seems like either answer is valid.

**Comment by mwyrzykowski** [comment]
cc @zoddicus who I think wrote these tests

**Comment by dneto0** [comment]
Your analysis looks good to me.  Thanks for spelling it out!
Yes, the intent is to allow either rounding in intermediate calculations.

I recommend taking your suggestion of accepting the alternative result.

I expect similar things will happen for determinate and other complex calculations.

**Comment by dneto0** [comment]
For my own reference, fnmsub docs can be found here:
https://developer.arm.com/documentation/dui0801/l/A64-Floating-point-Instructions/FNMSUB--A64- 

In particular (emphasis added)

> Floating-point Negated *fused* Multiply-Subtract (scalar):

Fused multiply-add (or sub) purposefully compute essentially infinitely accurate/precision intermediates, and can end up rounding differently.   This is a really nice thing to do!   We should definitely accept that result when the rest of the environment allows the full looseness of fast-math style floating point operations.

**Comment by zoddicus** [comment]
The WGSL spec has been changed to say that cross (and other AF operations with inherited accuracies) should defer to f32 accuracy intervals, https://www.w3.org/TR/WGSL/#abstract-float-accuracy. So I think this specific issue should be resolved due to wider acceptance intervals being used. Can you confirm this is no longer failing for you?

**Comment by mwyrzykowski** [comment]
That's right, https://gpuweb.github.io/cts/standalone/?q=webgpu:shader,execution,expression,call,builtin,cross:abstract_float:inputSource=%22const%22 is passing in WebKit now, so I think we can close this.
