### ISSUE TITLE
Expectation in dynamic_state.spec.ts does not align with the specification

### ISSUE THREAD

**Issue by mwyrzykowski** [gpuweb/cts#3307]
The test case on line 205 of dynamic_state.spec.ts: https://github.com/gpuweb/cts/blob/b7860c63a7b48de42198a79bae3aa0aa59bfb66e/src/webgpu/api/validation/encoding/cmds/render/dynamic_state.spec.ts#L205

does not seem to be in line with the specification. It lists:
```
{ minDepth: -0, maxDepth: -0 },
```
under the `success` category, but the specification for [setViewport](https://gpuweb.github.io/gpuweb/#dom-gpurenderpassencoder-setviewport) says:

> minDepth < maxDepth

`-0 < -0` would evaluate to false. If I instead test for `minDepth <= maxDepth`, the test case passes, but I think the `<=` is incorrect according to the specification. 

Do we have a bug in the specification wording or the CTS? cc @Kangz who last modified the line

**Comment by Kangz** [comment]
This seems like a bug in the WebGPU spec. I can't exactly recall exactly the discussions around this, but it seems the only constraint was reverse depth, not < vs <=. The D3D11 functional spec require <=, not < and that's the only constraint I have found (Vulkan doesn't have a constraint even in 1.0, and Metal docs say the two can be reversed).

**Comment by kainino0x** [comment]
No change needed.
