### ISSUE TITLE
Expectations in api,validation,capability_checks,limits,maxComputeWorkgroupStorageSize disagree with the WebGPU specification

### ISSUE THREAD

**Issue by mwyrzykowski** [gpuweb/cts#3352]
Unclear if this is a specification or a CTS issue.

In the validation for [createComputePipeline](https://gpuweb.github.io/gpuweb/#dom-gpudevice-createcomputepipeline), we see:
> Let workgroupStorageUsed be the sum of [roundUp](https://gpuweb.github.io/gpuweb/wgsl/#roundup)(16, [SizeOf](https://gpuweb.github.io/gpuweb/wgsl/#sizeof)(T)) over each type T of all variables with address space "[workgroup](https://gpuweb.github.io/gpuweb/wgsl/#address-spaces-workgroup)" [statically used](https://www.w3.org/TR/webgpu/#statically-used) by descriptor.[compute](https://www.w3.org/TR/webgpu/#dom-gpucomputepipelinedescriptor-compute).

The following test case:
https://gpuweb.github.io/cts/standalone/?q=webgpu:api,validation,capability_checks,limits,maxComputeWorkgroupStorageSize:createComputePipeline,at_over:limitTest=%22underDefault%22;testValueName=%22atLimit%22;async=false;wgslType=%22vec3%3Cf16%3E%22

is expected to pass. However, the shader in that test (the limit used is the default 16384):
```
enable f16;

    struct S1 {
      a: f32,
      b: vec4f,
      c: u32,
    };
    struct S2 {
      a: array<vec3f, 7>,
    };
    struct S3 {
      a: vec3f,
      b: vec2f,
    };
    var<workgroup> d0: array<vec3<f16>, 2047>;
    var<workgroup> d1: array<f32, 1>;
    @compute @workgroup_size(1) fn main() {
      _ = d0;
      _ = d1;
    }
```

which would exceed the expectation as:
> workgroupStorageUsed be the sum of [roundUp](https://gpuweb.github.io/gpuweb/wgsl/#roundup)(16, [SizeOf](https://gpuweb.github.io/gpuweb/wgsl/#sizeof)(T))
would expand to:
```
workgroupStorageUsed = roundUp(16, 8 * 2047) + roundUp(16, 4) = 16,384 + 16 = 16,400
```
If we omit rounding up to 16, then the test passes, as 8 * 2047 + 4 = 16380 but that seems to be in disagreement with the specification.

cc @greggman who I think authored this test

Is this my misunderstanding or is there a disagreement between the specification and the CTS here?

**Comment by greggman** [comment]
It's probably a bug in the test. I'll take a look

**Comment by mwyrzykowski** [comment]
Confirmed as fixed, closing
