### ISSUE TITLE
Two api,validation,gpu_external_texture_expiration tests fail due to issue PR 3312

### ISSUE THREAD

**Issue by mwyrzykowski** [gpuweb/cts#3364]
Running the following suite in Chrome:
https://gpuweb.github.io/cts/standalone/?debug=1&q=webgpu:api,validation,gpu_external_texture_expiration,*

fails because 
[startPlayingAndWaitForVideo](https://github.com/gpuweb/cts/blob/90b2eb7bbb45b805739d7da957ee173c3abb5bdd/src/webgpu/web_platform/util.ts#L362) added the following lines:
https://github.com/gpuweb/cts/blob/90b2eb7bbb45b805739d7da957ee173c3abb5bdd/src/webgpu/web_platform/util.ts#L373
https://github.com/gpuweb/cts/blob/90b2eb7bbb45b805739d7da957ee173c3abb5bdd/src/webgpu/web_platform/util.ts#L374

with b433131b07cccfcee23af5f7b210dd9bfa822e61 / https://github.com/gpuweb/cts/pull/3312

I think https://github.com/gpuweb/cts/pull/3312 should be reverted because it has changed the meaning of `startPlayingAndWaitForVideo` to something more, like `startPlayingAndWaitForVideoAndUnload`

Specifically https://gpuweb.github.io/cts/standalone/?debug=1&q=webgpu:api,validation,gpu_external_texture_expiration:use_import_to_refresh:* fails with `Failed to execute 'importExternalTexture' on 'GPUDevice': Failed to import texture from video element that doesn't have back resource.` and https://gpuweb.github.io/cts/standalone/?debug=1&q=webgpu:api,validation,gpu_external_texture_expiration:import_from_different_video_frame:* times out because the video src is empty string.

cc @shaoboyan @kainino0x @beaufortfrancois 

related to the discussion in https://github.com/gpuweb/cts/issues/3301

**Comment by shaoboyan** [comment]
Ah, thanks for reporting this. I think you're right about why these validation tests failed. Maybe we should has both `startPlayingAndWaitForVideo` and `startPlayingAndWaitForVideoAndUnload`. But I agree to revert that PR to unblock the CI first. @kainino0x @beaufortfrancois  WDYT?

**Comment by shaoboyan** [comment]
For myself, I'd like to try to use `trackForCleanUp` to reset `HTMLVideoElement`.

**Comment by mwyrzykowski** [comment]
This is passing now, closing
