### ISSUE TITLE
maxBindGroupsPlusVertexBuffers.spec.ts has invalid tests?

### ISSUE THREAD

**Issue by mwyrzykowski** [gpuweb/cts#3376]
Apologies as I did not catch this in the review, but unless I am missing a key point, it appears some of the tests added with maxBindGroupsPlusVertexBuffers.spec.ts are invalid.

They create a non-rasterizing shader module:
https://github.com/gpuweb/cts/blob/6493b876ade082dc4e4d883691e8900d5b42f01c/src/webgpu/api/validation/capability_checks/limits/maxBindGroupsPlusVertexBuffers.spec.ts#L88-L98

but then proceeds to attempt to create a render pipeline descriptor with a fragment module:
https://github.com/gpuweb/cts/blob/6493b876ade082dc4e4d883691e8900d5b42f01c/src/webgpu/api/validation/capability_checks/limits/maxBindGroupsPlusVertexBuffers.spec.ts#L115-L118

This should fail because the shader module has no fragment entry points, but descriptor.fragment is provided, per https://www.w3.org/TR/webgpu/#abstract-opdef-validating-gpurenderpipelinedescriptor

However the test expects the creation to succeed. 

I think lines 115-118 could be removed and the test would be valid:
https://github.com/gpuweb/cts/blob/6493b876ade082dc4e4d883691e8900d5b42f01c/src/webgpu/api/validation/capability_checks/limits/maxBindGroupsPlusVertexBuffers.spec.ts#L115-L118

what do you think @greggman ?

**Comment by greggman** [comment]
Sorry about that. I'll take a look.

**Comment by mwyrzykowski** [comment]
Looks good, closing
