### ISSUE TITLE
val: Test that two 'auto' BGLs at different group indices on the same pipeline are compatible

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#3388]
In that case we need to test that 2 bind groups that appear the same, are the same? In other words

```wgsl
      @group(0) @binding(0) var s1: sampler;
      @group(0) @binding(1) var t1: texture_2d<f32>;

      @group(1) @binding(0) var s2: sampler;
      @group(1) @binding(1) var t2: texture_2d<f32>;
```

If we use `layout: 'auto'` on this then a bindGroup made with `pipeline.getBindGroupLayout(0)` should work bound to bind group 1.

I don't think there is a test for that and it would be easy for browsers to disagree on this without a test?

_Originally posted by @greggman in https://github.com/gpuweb/cts/pull/3374#discussion_r1484908086_

**Comment by greggman** [comment]
https://github.com/gpuweb/cts/pull/3382
