### ISSUE TITLE
Move builtin must_use tests into per-builtin validation suites

### ISSUE THREAD

**Issue by jrprice** [gpuweb/cts#3502]
We have tests that the results of most builtins must be used in [must_use.spec.ts](https://github.com/gpuweb/cts/blob/main/src/webgpu/shader/validation/parse/must_use.spec.ts), but we have also started adding equivalent tests inside the per-builtin validation suites, e.g. #3496.

We should probably move all of these must_use tests into the per-builtin suites to make it clearer what should be covered when adding a new builtin. The dedicated `must_use` suite would then focus on user-specified `@must_use` attributes.

**Comment by alan-baker** [comment]
Don't neglect `src/webgpu/shader/validation/expression/call/builtin/value_constructor.spec.ts`.
