### ISSUE TITLE
`webgpu:shader,execution,expression,unary,address_of_and_indirection:deref` for `f16` are failing

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/cts#3514]
It would appear that one of the CLs in https://github.com/gpuweb/cts/pull/3462 may have broken these tests:

https://github.com/gpuweb/cts/commit/3e45aee0b16dc724a79a0feb0490e2ddb06c9f0d - Add ArrayType / ArrayValue
https://github.com/gpuweb/cts/commit/b9fda017e5f316d9bcc7e11be6aec9216aeaf9f5 - Refactor Value and Types
https://github.com/gpuweb/cts/commit/ac1af685a3ae08e89d22c5497c56cab6453c9ab2 - Split the 'Scalar' class into one class per type

**Comment by dneto0** [comment]
Testing on a mac, it appears to be https://github.com/gpuweb/cts/commit/ac1af685a3ae08e89d22c5497c56cab6453c9ab2 - Split the 'Scalar' class into one class per type
