### ISSUE TITLE
Condense capability info tables to be more readable/authorable

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#354]
_Originally posted by @kainino0x in https://github.com/gpuweb/cts/pull/352#discussion_r523300691_

---

I don't think it makes sense to split it here in such a way that it affects other files, just for the sake of making this file more editable. I think it's okay if this file is a little special (have to zoom out your editor maybe).

Maybe we could come up with a little table-making helper thing so we don't have to repeat "renderable:" "color:" etc on every line?

---

`componentType` can be computed from `dataType` right? So we could separate that into a separate table. Or use `, ...kDataTypeUnorm` where `const kDataTypeUnorm = { dataType: 'unorm', componentType: 'float' };`.

Let's consider both of these as followups.

**Comment by austinEng** [comment]
> componentType can be computed from dataType right?

except maybe not depth-stencil but that could be special cased

also, something we'll have to consider as well is whether or not we want the tables to work well for combined depth/stencil formats. i.e. We'll need per-aspect information. I guess those formats are mostly located in separate tables right now so it should be ok to specialize them there.

> Maybe we could come up with a little table-making helper thing so we don't have to repeat "renderable:" "color:" etc on every line?

this makes sense, also most of the blockSize = 1 formats
