### ISSUE TITLE
Service worker mode not working in standalone in static deployment

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#3583]
For example, on <https://gpuweb.github.io/cts/standalone/?worker=service&q=webgpu:examples:basic:> on Chrome Canary on Mac:

`TypeError: Failed to register a ServiceWorker for scope ('https://gpuweb.github.io/out/webgpu/webworker/') with script ('https://gpuweb.github.io/out/webgpu/webworker/examples.worker.js'): A bad HTTP response code (404) was received when fetching the script.`

**Comment by kainino0x** [comment]
cc @beaufortfrancois

**Comment by beaufortfrancois** [comment]
It looks like the correct URL should be `https://gpuweb.github.io/cts/out/webgpu/webworker/examples.worker.js` not `https://gpuweb.github.io/out/webgpu/webworker/examples.worker.js`. 
TDLR; The `/cts` is missing before `/out`.

**Comment by kainino0x** [comment]
Ah yeah, that's definitely it. Looks like `worker_launcher.ts` probably gets this right but `test_worker.ts` doesn't. I think that was my bad with the relative `new URL()` thing.

**Comment by kainino0x** [comment]
Verified fixed on gpuweb.github.io.
