### ISSUE TITLE
error in webgpu:shader,execution,expression,access,structure,index:const_nested:member_types

### ISSUE THREAD

**Issue by greggman** [gpuweb/cts#3654]
webgpu:shader,execution,expression,access,structure,index:const_nested:member_types=

["i32","u32","f32","f16","vec3f","vec4i"] - fail:
  - EXCEPTION: Error: Unexpected validation error occurred: Binding size (2) of [Buffer (unlabeled)] isn't a multiple of 4 when binding type is (BufferBindingType::Storage).
     - While validating entries[0] as a Buffer.

Seems like an error in the test?

**Comment by kainino0x** [comment]
Found this in the roll and verified locally as well.

**Comment by kainino0x** [comment]
Actually more broadly - it's in a bunch of tests in this file.

**Comment by kainino0x** [comment]
From PR #3641

**Comment by ben-clayton** [comment]
Fixed.
