### ISSUE TITLE
errors in webgpu:shader,execution,expression,constructor,non_zero:*

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#3657]
Example:
`webgpu:shader,execution,expression,constructor,non_zero:abstract_array_elements:abstract_type="abstract-int";concrete_type="f32";length=1`

`EXCEPTION: Error: Unexpected validation error occurred: Error while parsing WGSL: :22:22 error: cannot assign 'array<i32, 1>' to 'array<f32, 1>'`

Found in CTS->Dawn roll. It sounds like a test bug, I don't think this is supposed to be valid.

All of the following are failing with similar errors locally (M1 Mac, Chrome `125.0.6415.0 (Official Build) canary (arm64) `):

```
webgpu:shader,execution,expression,constructor,non_zero:abstract_vector_splat:*
webgpu:shader,execution,expression,constructor,non_zero:abstract_vector_elements:*
webgpu:shader,execution,expression,constructor,non_zero:abstract_vector_mix:*
webgpu:shader,execution,expression,constructor,non_zero:abstract_matrix_elements:*
webgpu:shader,execution,expression,constructor,non_zero:abstract_matrix_column_vectors:*
webgpu:shader,execution,expression,constructor,non_zero:abstract_array_elements:*
```

From #3631

**Comment by kainino0x** [comment]
Tangentially(?) this test is unexpectedly passing on most configurations on Chrome's CQ: https://bugs.chromium.org/p/dawn/issues/detail?id=2514

**Comment by kainino0x** [comment]
IIUC fixed in #3659? @ben-clayton

**Comment by ben-clayton** [comment]
I believe so, but we might want to wait until the next roll confirms.

**Comment by kainino0x** [comment]
The roll did not remove the expectations:
https://dawn-review.googlesource.com/c/dawn/+/184140/4/webgpu-cts/expectations.txt#1483

And locally they still fail with `unroll_const_eval_loops` disabled (and pass with it enabled).

**Comment by ben-clayton** [comment]
Argh. Okay. I'll take another look tomorrow. Sorry about that.

**Comment by kainino0x** [comment]
Thanks!

**Comment by ben-clayton** [comment]
Fixed.
