### ISSUE TITLE
`webgpu:api,operation,labels:wrappers_do_not_share_labels:*` calls `createRenderPipeline` with no target

### ISSUE THREAD

**Issue by jimblandy** [gpuweb/cts#3754]
The algorithm `validatingGPURenderPipelineDescriptor` says:

> - There must exist at least one attachment, either:
>
>     - A non-null value in descriptor.[fragment](https://gpuweb.github.io/gpuweb/#dom-gpurenderpipelinedescriptor-fragment).[targets](https://gpuweb.github.io/gpuweb/#dom-gpufragmentstate-targets), or
>
>     - A descriptor.[depthStencil](https://gpuweb.github.io/gpuweb/#dom-gpurenderpipelinedescriptor-depthstencil).

But [`webgpu:api,operation,labels:wrappers_do_not_share_labels:*`][test] tries to create a render pipeline without any attachments:

```typescript
    const pipeline = t.device.createRenderPipeline({
      layout: 'auto',
      vertex: {
        module,
        entryPoint: 'main',
      },
    });
```

[test]: https://github.com/gpuweb/cts/blob/007e1015875a0a91794edbc14feb3ad5fe60f90b/src/webgpu/api/operation/labels.spec.ts#L264-L270

**Comment by kainino0x** [comment]
Thank you for catching this!
I am surprised that Dawn passes this test. I thought we had tests for this validation. I'm pretty sure we do for render passes, I guess we missed it for render pipelines. I have filed https://crbug.com/341812551

We'll also of course need to test that, since I guess we're not testing it.

**Comment by Kangz** [comment]
This is expect, the WebGPU spec says:

> fragment, of type [GPUFragmentState](https://gpuweb.github.io/gpuweb/#dictdef-gpufragmentstate)
>  Describes the fragment shader entry point of the [pipeline](https://gpuweb.github.io/gpuweb/#pipeline) and its output colors. If not [provided](https://infra.spec.whatwg.org/#map-exists), the [§ 23.3.8 No Color Output](https://gpuweb.github.io/gpuweb/#no-color-output) mode is enabled.

**Comment by ErichDonGubler** [comment]
@Kangz: In that case, a depth-stencil attachment should still be specified, yes, per the spec. text in the OP?

**Comment by Kangz** [comment]
Ah my bad, yes that's the case.

**Comment by ErichDonGubler** [comment]
Resolved with https://github.com/gpuweb/cts/pull/3756. I've filed an issue for validating this specific case at https://github.com/gpuweb/cts/issues/3755.
