### ISSUE TITLE
Test clip-distances feature

### ISSUE THREAD

**Issue by dneto0** [gpuweb/cts#3773]
The spec change has landed. https://github.com/gpuweb/gpuweb/pull/4588  

---

Particular things to test:
- [ ] maxInterStageShaderVariables

**Comment by kainino0x** [comment]
We should make sure to carefully test the rules around `maxInterStageShaderVariables`. I am working on #4688 and the rule for `clip_distances` says that it consumes 1-2 `@location`s at the end, not just uses 1-2 variables from the limit (compare with `"point-list"` which uses 1 from the limit but doesn't use any `@location`s).
