### ISSUE TITLE
test validation of "one-handed rules": error required based on value of 1 arg when the operation has 2 or more (or K, and  N>K)

### ISSUE THREAD

**Issue by dneto0** [gpuweb/cts#3778]
Example: Integer division `e1 / e2` has rules like this:

> If T is a signed [integer scalar](https://gpuweb.github.io/gpuweb/wgsl/#integer-scalar) type, evaluates to:

> - If e2 is zero:

>-  It is a [shader-creation error](https://gpuweb.github.io/gpuweb/wgsl/#shader-creation-error) if e2 is a [const-expression](https://gpuweb.github.io/gpuweb/wgsl/#const-expressions).

>-  It is a [pipeline-creation error](https://gpuweb.github.io/gpuweb/wgsl/#pipeline-creation-error) if e2 is an [override-expression](https://gpuweb.github.io/gpuweb/wgsl/#override-expressions).

> - Otherwise, e1.

We need CTS coverage for cases where `e1` is a runtime expression, and `e2` is const-expression 0 or override-expression 0. Those should trigger an error:

Example:
```
override zero = 0;
fn foo() {
  let a = 1;
  let b = a / 0; // shader-creation error
  let c = a / zero; // pipeline-creation error if foo is in the shader stage and 'zero' is not substituted at pipeline creation time.
}
```

Partial eval locations:
- [x] vector access expressions
- [x] matrix access expressions
- [x] array access expressions
- [x] integer division rhs
- [x] integer modulo rhs
- [x] shift expressions rhs
- [ ] conversion constructors with multiple parameters
- [x] clamp low > high
- [x] extractBits count + offset > width(T)
- [x] insertBits count + offset > width(T)
- [x] ldexp e2 > bias + 1
- [x] smoothstep low >= high
- [x] textureGather component [0,3]
- [x] texture functions with offset [-8, 7]
  - [ ] textureGather
  - [ ] textureGatherCompare
  - [ ] textureSample
  - [ ] textureSampleBias
  - [ ] textureSampleCompare
  - [ ] textureSampleCompareLevel
  - [ ] textureSampleGrad
  - [ ] textureSampleLevel

**Comment by dneto0** [comment]
We first need a survey of which operations/builtins have such "one-handed" rules.

example:
* [Vector single component selection with array-index syntax](https://gpuweb.github.io/gpuweb/wgsl/#vector-single-component): `v[i]` where i is const or override

**Comment by alan-baker** [comment]
I believe these are the instances where there are errors without full information:
* vector access expressions
* matrix access expressions
* array access expressions
* integer division rhs
* integer modulo rhs
* shift expressions rhs
* conversion constructors with multiple parameters
* clamp low > high
* extractBits count + offset > width(T)
* insertBits count + offset > width(T)
* ldexp e2 > bias + 1
* smoothstep low >= high
* textureGather component [0,3]
* texture functions with offset [-8, 7]
  * textureGather
  * textureGatherCompare
  * textureSample
  * textureSampleBias
  * textureSampleCompare
  * textureSampleCompareLevel
  * textureSampleGrad
  * textureSampleLevel

Some of these might already be validated.

**Comment by alan-baker** [comment]
As far as I can tell all these cases are now tested in CTS.
