### ISSUE TITLE
Rejection on createComputePipelineAsnyc causes timout in tests

### ISSUE THREAD

**Issue by sagudev** [gpuweb/cts#3809]
this happens because rejection is not handled. Example: https://github.com/gpuweb/cts/blob/85678b29c04094891969356a717135fd838927d8/src/webgpu/shader/execution/expression/expression.ts#L1179
 (there are more such places).

You can see live example here: [https://sagudev.github.io/cts/standalone/?runnow=1&q=webgpu:shader,execution,expression,binary,f32_subtraction:scalar_vector:inputSource=%22const%22;*](https://sagudev.github.io/cts/standalone/?runnow=1&q=webgpu:shader,execution,expression,binary,f32_subtraction:scalar_vector:inputSource=%22const%22;*) which has rejection hard-coded https://github.com/sagudev/cts/commit/615b9437fa3ceedaef3d27a7f00aa1ea4e39c5e8 (reproducible on Edge).

This is problem in servo because some things are not supported yet (so promise does reject).

**Comment by sagudev** [comment]
related https://github.com/gpuweb/cts/issues/3157

**Comment by kainino0x** [comment]
Thanks for the report, definitely something going wrong here.

Because the promise is created before it's awaited, this is causing an unhandledrejection (see #3159). I don't know why that results in a hang, though - the intent was that it would eventually reach the `await Promise.all(pendingBatches)` line and the test should fail.

**Comment by sagudev** [comment]
It looks like that we never reach `await Promise.all(pendingBatches)` on rejection, because `if (batchesInFlight > maxBatchesInFlight) {` happens. I think the main reason hang happens is because `void t.queue.onSubmittedWorkDone().finally(batchFinishedCallback);` is never called when `const checkBatch = await submitBatch(t, shaderBuilder, shaderBuilderParams, pipelineCache);` rejects.

**Comment by sagudev** [comment]
So the timeout was caused by never resolving https://github.com/gpuweb/cts/blob/f752c7515376487493ff22a5e1aed4d6212a6983/src/webgpu/shader/execution/expression/expression.ts#L428 as `batchFinishedCallback` was never called, due to rejection on https://github.com/gpuweb/cts/blob/f752c7515376487493ff22a5e1aed4d6212a6983/src/webgpu/shader/execution/expression/expression.ts#L414 the solution is to move the callback to https://github.com/gpuweb/cts/blob/f752c7515376487493ff22a5e1aed4d6212a6983/src/webgpu/shader/execution/expression/expression.ts#L433 (and it also belongs there conceptually, as it only deals with decreasing `batchesInFlight`).

**Comment by sagudev** [comment]
Fixed in #3844.
