### ISSUE TITLE
wgsl: Add execution test for @interpolate(flat,first), and validation tests for `either` and `first`

### ISSUE THREAD

**Issue by dneto0** [gpuweb/cts#3818]
Related: #3815   (which is an execution test)

Spec change was: https://github.com/gpuweb/gpuweb/pull/4639 

For validation add to tests at `webgpu:shader,validation,shader_io,interpolate:*`
* 'either' and 'first' can only be used with 'flat' interpolation and not in combination.

**Comment by greggman** [comment]
validation tests have already been added

src/webgpu/shader/validation/shader_io/interpolate.spec.ts

tests every combination of type and sampling and expects valid combos to pass and invalid to fail and the rest of the tests do similar.

**Comment by greggman** [comment]
execution tests have been added

https://github.com/gpuweb/cts/pull/3822
