### ISSUE TITLE
`npm run wpt` generates `*.worker.js` tests that accidentally get run by `wptrunner`

### ISSUE THREAD

**Issue by ErichDonGubler** [gpuweb/cts#3834]
`*.worker.js` files are included in `out-wpt/` output generated by `npm run wpt`. This file extension appears to have been settled on in isolation from consideration of WPT tests, which _actually_ treat `*.worker.js` files as a form of test specification (see WPT upstream docs' section titled ["Dedicated worker tests (`.worker.js`)"](https://web-platform-tests.org/writing-tests/testharness.html#dedicated-worker-tests-worker-js).

We need to move away from this file extension for worker tests that aren't intended to be run in WPT.

**Comment by ErichDonGubler** [comment]
@kainino0x suggested in a DM conversation with me that that it would be clearer to make a uniform change of file extension across all testing targets.

**Comment by ErichDonGubler** [comment]
Bug experience report: Mozilla has run into this in CI, and worked around this by marking these unintended test specs. as `disabled: true` in a `__dir__.ini` WPT metadata entry.

**Comment by ErichDonGubler** [comment]
This appears to not actually be solved yet; `npm run wpt` now generates `*.as_worker.js` tests _in addition to_ (rather than _instead of_) the originally offending `*.worker.js` tests. 🤔

**Comment by kainino0x** [comment]
That's surprising as I don't see any in https://github.com/gpuweb/cts/tree/gh-pages/out-wpt/webgpu/webworker

Could you check that your build directory is getting wiped before build? Otherwise the old files could still be leftover.

**Comment by ErichDonGubler** [comment]
I was able to reproduce this on one of my machines for some time, but after updating to latest `main` and very forcibly using `git clean -xdf`, I believe I was running into local issues. Sorry for the noise!

**Comment by ErichDonGubler** [comment]
After running into this on another machine, I did a bit more investigation: it turns out that old copies of `*.worker.js` files had been placed in my local (`.gitignore`'d) `gen/` directory. I only needed to remove that folder, and then only `*.as_worker.js` were present, as expected.

Seems like this might be a cache coherency problem with the `gen/` folder's contents, if `gen/` is supposed to be a cache?

**Comment by kainino0x** [comment]
Ahh, that explains it. It's not exactly a cache, we just have a directory for it because we use its output multiple times. But, like `out`, it does need to be cleared, because we copy everything out of it (not just the files we expect to generate there).

**Comment by kainino0x** [comment]
It is cleaned by `npx grunt clean` which is the first step of `npx grunt all` (== `npm test` == `npm run all`) but it's not included any of the other smaller build commands.

**Comment by kainino0x** [comment]
Opened a fix. Thank you for debugging this!
