### ISSUE TITLE
Deployment broken

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#398]
Not sure why exactly, but it seems like a file is missing.
https://gpuweb.github.io/cts/standalone/

cc @austinEng @mehmetoguzderin probably related to the work one of you has been doing?

**Comment by kainino0x** [comment]
https://gpuweb.github.io/cts/out/webgpu/util/texture/texel_data.js is the missing file

**Comment by mehmetoguzderin** [comment]
I don't think there are any reasons for Actions to specifically omit that file but I will check to see if there is anything indirect triggered by them

**Comment by kainino0x** [comment]
OK, looking into it. The files are definitely missing from the gh-pages branch. Likely not getting added to the index properly.

**Comment by kainino0x** [comment]
Somehow the `sed` commands seem not to be working? The `.gitignore` in the `gh-pages` branch still has out/ and out-wpt/ in it.

**Comment by kainino0x** [comment]
Okay, that didn't work.

**Comment by austinEng** [comment]
Does it have something to do with the names maybe? texel_data.ts and texel_data.spec.ts have the same base name

**Comment by kainino0x** [comment]
I don't think so; #402 deleted all the generated files from gh-pages and #403 reverted it, but all of the generated files are still gone. It's just not finding and adding new files to the index.

**Comment by kainino0x** [comment]
#404 fixed it!
