### ISSUE TITLE
`webgpu:shader,validation,parse,diagnostic:duplicate_attribute_same_location:*` expects failure when `s1` and `s2` are the same, but should succeed

### ISSUE THREAD

**Issue by ErichDonGubler** [gpuweb/cts#4041]
According to the WGSL spec.:

> Two [diagnostic filters](https://www.w3.org/TR/WGSL/#diagnostic-filter) conflict when:
> 
> -   (_AR1_ = _AR2_), and
>     
> -   (_TR1_ = _TR2_), and
>     
> -   (_NS1_ ≠ _NS2_).

...where `NS1` and `NS2` correspond to the `s1` and `s2` matrix values in `webgpu:shader,validation,parse,diagnostic:duplicate_attribute_same_location:*`. This means that when `s1 === s2` in the `duplicate_attribute_same_location` test, we should expect success, in addition to the cases already expected where `same_rule === false`.

**Comment by alan-baker** [comment]
The attribute has an additional rule:
> More than one [diagnostic](https://gpuweb.github.io/gpuweb/wgsl/#attribute-diagnostic) attribute may be specified on a syntactic form, but they [must](https://gpuweb.github.io/gpuweb/wgsl/#shader-creation-error) specify different [triggering rules](https://gpuweb.github.io/gpuweb/wgsl/#diagnostic-triggering-rule).

So same severity is allowed for the global filter, but disallowed for attributes.

**Comment by ErichDonGubler** [comment]
Oof! My mistake, it seems. 😩 Thanks for the patient response.
