### ISSUE TITLE
test duplicate (non-conflicting) diagnostics directives

### ISSUE THREAD

**Issue by dneto0** [gpuweb/cts#4045]
See https://github.com/gpuweb/gpuweb/issues/4976

**Comment by jrprice** [comment]
This test covers conflicting diagnostic directives:
https://github.com/gpuweb/cts/tree/327fb7b053d9667904ac45b8e5d33d6e6392b023/src/webgpu/shader/validation/parse/diagnostic.spec.ts#L153-L162

It checks that conflicting diagnostic directives are allowed only when their severities are the same.

**Comment by dneto0** [comment]
Aha! thanks!

Closing
