### ISSUE TITLE
Emit worker tests for WPT

### ISSUE THREAD

**Issue by ErichDonGubler** [gpuweb/cts#4098]
Currently, CTS doesn't emit meaningful coverage for worker functionality with the WPT target. For platforms depending on WPT coverage (like Firefox), this is blocking criteria for shipping.

**Comment by kainino0x** [comment]
There is a way to do this via the config file for `gen_wpt_cts_html`, e.g.:
```
  "argumentsPrefixes": [
    "?worker=dedicated&q=",
    "?worker=shared&q=",
    "?worker=service&q="
  ],
```
(see the script for config file documentation, and see `tools/gen_wpt_cfg_unchunked.json` for an example)

However this will run EVERY test on every worker type. In Chromium we only run a few tests on workers. I will update that script it can take a list of test queries as well. Probably will have that out later today.

**Comment by kainino0x** [comment]
@ErichDonGubler I landed a PR, please let me know if you can make that work, or if anything is missing.

**Comment by ErichDonGubler** [comment]
@kainino0x: I'm attempting to consume the newly emitted `cts-withsomeworkers.https.html` for Firefox's CI (see [bug 1904364, comment 9](https://bugzilla.mozilla.org/show_bug.cgi?id=1904364#c9)). It looks promising so far! I consider this issue resolved.

I may have a follow-up bug report for service workers, once I determine which technology is at fault for CTS not running in service workers on Firefox. 😅 When using the standalone CTS runner (i.e., with [`webgpu:api,operation,adapter,info:same_object:`](https://gpuweb.github.io/cts/standalone/?worker=service&debug=1&q=webgpu:api,operation,adapter,info:same_object:)), I'm currently getting errors of the form:

```
EXCEPTION: TypeError: ServiceWorker script at https://gpuweb.github.io/cts/out/webgpu/webworker/api/operation/adapter/info.as_worker.js for scope https://gpuweb.github.io/cts/out/webgpu/webworker/api/operation/adapter/ threw an exception during script evaluation.
```

**Comment by kainino0x** [comment]
Discussing this a bit on matrix but for the record:

Firefox doesn't support "module" service workers:
https://bugzilla.mozilla.org/show_bug.cgi?id=1360870

I think it's theoretically possible for us to avoid them in either of two ways:

- for each `*.as_worker.js`, instead of using modules, run a bundler to bundle all of its dependencies into one file. Of course this would make each `*.as_worker.js` really large.
- similar, but at coarser granularity. Up to having just one bundle containing _all_ of the tests, and loading the whole thing for every test.

**Comment by ErichDonGubler** [comment]
I've been playing with making this work for CI in Firefox, and it looks pretty promising so far! Except for service workers not working ([no module script support for those in Firefox](https://matrix.to/#/!MFogdGJfnZLrDmgkBN:matrix.org/$j8VFZwasS9gF5wNzC_mDgCF3_RyP4SxVXYa3Uheo1WU?via=matrix.org&via=mozilla.org&via=matrix.im), waiting on [bug 1360870](https://bugzilla.mozilla.org/show_bug.cgi?id=1360870)), this lets us choose the coverage we want for workers. I'd say we're satisfied for now, thanks!
