### ISSUE TITLE
Test that the alpha:true/false of canvas is honored

### ISSUE THREAD

**Issue by Kangz** [gpuweb/cts#460]
This came up in a Chromium issue where rendering alpha:zero in an alpha:false canvas still made the canvas transparent. We should have reftests that check this is correctly handled.

**Comment by kainino0x** [comment]
I thought WebGPU doesn't allow alpha:false (or premultipliedAlpha:false or preserveDrawingBuffer:true) at all. Does Chromium allow it to be configured?

**Comment by Kangz** [comment]
Currently it does, though if the group decided that `alpha:false` isn't a thing then we should just disallow it in Chromium.

**Comment by kainino0x** [comment]
This is now being tracked more widely in https://crbug.com/dawn/917
