### ISSUE TITLE
webgpu:api,operation,sampling,anisotropy:* uses invalid WGSL

### ISSUE THREAD

**Issue by austinEng** [gpuweb/cts#513]
Error: Unexpected validation error occurred: Tint WGSL reader failure:
Parser: error: 26:27 error: type in vector constructor does not match vector type: expected 'f32', found 'i32'
                vec4<f32>(0, -43.63650894165039, -43.232173919677734, -43.18894577026367),
                          ^

Shader: 

            [[builtin(vertex_index)]] var<in> VertexIndex : i32;
            [[builtin(position)]] var<out> Position : vec4<f32>;
            [[location(0)]] var<out> fragUV : vec2<f32>;

            [[stage(vertex)]] fn main() -> void {
              const position : array<vec3<f32>, 6> = array<vec3<f32>, 6>(
                vec3<f32>(-0.5, 0.5, -0.5),
                vec3<f32>(0.5, 0.5, -0.5),
                vec3<f32>(-0.5, 0.5, 0.5),
                vec3<f32>(-0.5, 0.5, 0.5),
                vec3<f32>(0.5, 0.5, -0.5),
                vec3<f32>(0.5, 0.5, 0.5));
              // uv is pre-scaled to mimic repeating tiled texture
              const uv : array<vec2<f32>, 6> = array<vec2<f32>, 6>(
                vec2<f32>(0.0, 0.0),
                vec2<f32>(1.0, 0.0),
                vec2<f32>(0.0, 50.0),
                vec2<f32>(0.0, 50.0),
                vec2<f32>(1.0, 0.0),
                vec2<f32>(1.0, 50.0));
              // draw a slanted plane in a specific way
              const matrix : mat4x4<f32> = mat4x4<f32>(
                vec4<f32>(-1.7320507764816284, 1.8322050568049563e-16, -6.176817699518044e-17, -6.170640314703498e-17),
                vec4<f32>(-2.1211504944260596e-16, -1.496108889579773, 0.5043753981590271, 0.5038710236549377),
                vec4<f32>(0, -43.63650894165039, -43.232173919677734, -43.18894577026367),
                vec4<f32>(0, 21.693578720092773, 21.789791107177734, 21.86800193786621));

              fragUV = uv[VertexIndex];
              Position = matrix * vec4<f32>(position[VertexIndex], 1.0);
            }

**Comment by austinEng** [comment]
@shrekshao

**Comment by shrekshao** [comment]
`vec4<f32>(0, -43.63650894165039, -43.232173919677734, -43.18894577026367)` -> `vec4<f32>(0.0, -43.63650894165039, -43.232173919677734, -43.18894577026367)` ?

**Comment by austinEng** [comment]
yea, I think it's just missing the ".0" suffix.

**Comment by shrekshao** [comment]
Small fix at #514
