### ISSUE TITLE
wgsl: validate identifier token pattern

### ISSUE THREAD

**Issue by dneto0** [gpuweb/cts#748]
For example, identifiers starting with an underscore must be disallowed.  https://gpuweb.github.io/gpuweb/wgsl/#identifiers 

Tint bug: https://bugs.chromium.org/p/tint/issues/detail?id=1179 and [fix](https://dawn-review.googlesource.com/c/tint/+/64464)

Naga bug: https://github.com/gfx-rs/naga/issues/1386

**Comment by dj2** [comment]
The example of leading underscore is no longer valid as that's accepted in the spec. But, there are other cases now that we can have unicode identifiers that need to be added to the CTS as they aren't tested currently.

**Comment by dj2** [comment]
Fixed.
