### ISSUE TITLE
Enhance the wgsl type generator 

### ISSUE THREAD

**Issue by sarahM0** [gpuweb/cts#763]
@ben-clayton : Ideally, the _kTypeInfo would actually provide another TypeInfo for the element type, which could describe the kind of the element. I think this would simplify a lot of this kind of logic (noted in #762 ).
@austinEng : what if elementBaseType were a full _kTypeInfo as well? could be useful if/when we have nested containers (suggested in #731 ).

**Comment by dj2** [comment]
This has been sitting for a while, and I don't think there are any plans to change at the moment. Going to close this. If it comes up as an issue again we can re-open.
