### ISSUE TITLE
Don't test depth stencil formats in color formats tests

### ISSUE THREAD

**Issue by beaufortfrancois** [gpuweb/cts#77]
"color formats must be renderable" test fails because depth stencil format were added in https://github.com/gpuweb/cts/commit/840ff3f152ae1d1192fa1273cb684e8e7e033e8a#diff-a4c78fe12bb75d8679eab0ed0211c06d while they were not part of the original test.

![Screen Shot 2019-10-25 at 9 42 12 AM](https://user-images.githubusercontent.com/634478/67552646-c1d25a00-f70b-11e9-81fe-d25b863a8d4d.png)

**Comment by kainino0x** [comment]
Whoops. I think we should still test them - just add the necessary metadata to the format info table so we can say "should error". (e.g. `color: boolean` or something)
