### ISSUE TITLE
How should accuracy of floating point builtins be evaluated?

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#792]
Currently the WGSL spec specifies the accuracy required for a variety of FP builtins, https://www.w3.org/TR/WGSL/#floating-point-accuracy

A large number of them resolve down to an accuracy in terms of ULP, which can be then converted into a concrete epsilon that values should be within to the true value.

The issue becomes, what is the true value?
Is it the JS/Typescript value for that specific operation?
Is it from a table of values generated offline via a precision C math library? Maybe generated as part of the build process for the CTS?
Is there some other source of truth?

Additionally, how many values do we test it against, just a set of specific interesting values, all the potential values, or maybe a random selection of values?

Instead of having the tests for each builtin figure this out for themselves, and potentially be inconsistent with each other, there should probably be a standardized way of doing this, and probably a related doc outlining it.

**Comment by zoddicus** [comment]
Additionally how should tests test for accuracy when it is defined as inherited from another function?

For example:
`asin`'s accuracy is `Inherited from atan2(x, sqrt(1.0 - x * x))`
`atan2`'s accuracy is `4096 ULP`
`sqrt`'s accuracy is `Inherited from 1.0 / inverseSqrt(x)`
`inverseSqrt`'s accuracy is `2 ULP`

**Comment by dneto0** [comment]
Let's talk about ECMAScript first:

- a Number is the same as IEEE-754 binary64 (double precision float).
- the Math object provides things like sin, cos, atan, etc.   All the interesting ones are declared to be [implementation-approximated](https://tc39.es/ecma262/#implementation-approximated):
   > An _implementation-approximated_ facility is one that defers its definition to an external source while recommending an ideal behaviour. While conforming implementations are free to choose any behaviour within the constraints put forth by this specification, they are encouraged to strive to approximate the ideal.
- basic arithmetic is provided by the Number object. It describes edge cases (infinities, +0, -0,NaNs).  It doesn't describe accuracy requirements, but defers to IEEE-754. 
    - I looked at IEEE-754.  I'm not 100% certain but it seems to imply requiring correctly rounded results for add, sub, mul, div, and sqrt.
    - C++14 says "Since this International Standard imposes no restrictions on the accuracy of floating-point operations..."  which goes entirely in the opposite direction.

So, in principal we can't guarantee consistency across implementations for JavaScript math. That's my reading.

Pragmatically, I wonder if ecosystem forces have made double-precision float accuracy close enough across implementations so that any particular result is within 1ULP _after converting to single-precision float_.  I just don't know.  But if we *assume* that then we can make forward progress:  Assume the JavaScript result is "correct".

**Comment by dneto0** [comment]
A second consideration is: What values to sample from the domain of each function:
Options include:
- exhastive (or close). 
    -  E.g.  for unary functions over floating point types (e.g. cosine), OpenCL conformance testing is *exhaustive*, i.e. 4billion samples.  This doesn't extend to functions with more than one parameter, though.
- sparse sampling:
    - random
    - evenly spaced
    - carefully chosen general edge cases (e.g. 0, 1, machine epsilon, chosen subnormals or very small magnitude, very large magnitude); both positive and negative.
           - approximation can be difficult near extremely large or small magnitude values.
    - edge cases chosen per function: 
           - edge of the domain, if any. 
           - points of maximum slope, or very near divergence points, specific to each function.  Approximation can be more difficult here.
          

Test time is a concern, so exhaustive is not pragmatic (unless its <1000-ish samples).

So I think we have to go with sparse sampling.   I think it's reasonable to go with all the sparse strategies that are independent of the target function.  We may need an investigation for each function:
- domain.  e.g. sqrt is defined for x >= 0.   (I learned that by IEEE-754, sqrt of negative zero is supposed to be negative zero)
- regions of maximum slope.

**Comment by dneto0** [comment]
What does it mean to "inherit" accuracy bounds from a formula?

From [Vulkan: Precision and Operation of SPIR-V Instructions](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#spirvenv-precision-operation), subsection at "Inherited From...":

> Where an operation’s precision is described as being inherited from a formula, the result returned must be at least as accurate as the result of computing an approximation to x using a formula equivalent to the given formula applied to the supplied inputs. 
> Specifically, the formula given may be transformed using the mathematical associativity, commutativity and distributivity of the operators involved to yield an equivalent formula. 
> The SPIR-V precision rules, when applied to each such formula and the given input values, define a range of permitted values. If NaN is one of the permitted values then the operation may return any result, otherwise let the largest permitted value in any of the ranges be Fmax and the smallest be Fmin. The operation must return a value in the range [x - E, x + E] where E=max(|x−F<sub>min</sub>|, x−F<sub>max</sub>|)
> If the entry point is declared with the DenormFlushToZero execution mode, then any intermediate denormal value(s) while evaluating the formula may be flushed to zero. Denormal final results must be flushed to zero. 
> If the entry point is declared with the DenormPreserve execution mode, then denormals must be preserved throughout the formula.

So, basically, for each sampled point X:
- evaluate golden results for the leaf terms of the given formula
- transform each of those point results into intervals based on spec-defined ULPs and/or permitted rounding modes (for correctly rounded terms)
- Then evaluate the formula, but operating on intervals.

I confirmed this is what the Vulkan conformance tests do.  The algorithm for evaluating a function G at an interval [a,b] is:
- first assume monotonicity, and evaluate at the endpoints:    [ min(G(a),G(b)), max(G(a),G(b) ]
- but G might not be monotonic over [a,b], so expand the interval by querying the "internal extrema" over (a,b).

So in addition to being able to compute G, you need special knowledge of how to compute internal extrema, i.e. max  
G(h) for  a <= h <= b.

The "inherited from" formulas in WGSL use:
- atan2
- sqrt
- multiply
- constant 1.0, 0.5, 2.0, 3.0
- subtraction
- exp
- length
- add
- divide
- sin
- cos
- sinh ( which itself uses inheritance)
- cosh (which itself uses inheritance
