### ISSUE TITLE
add 'create' method for ScalarType WGSL builtins testing framework

### ISSUE THREAD

**Issue by dneto0** [gpuweb/cts#829]
Implement ideas at https://github.com/gpuweb/cts/pull/828/files#r744857600

**Comment by dneto0** [comment]
cc: @ben-clayton

**Comment by ben-clayton** [comment]
The types in https://github.com/gpuweb/cts/blob/main/src/webgpu/util/conversion.ts serve this purpose (but the file needs splitting up into sensibly named files!)

Closing as done.
