### ISSUE TITLE
val: queue,destroyed,buffer

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#879]
Comment 4 by zhaoming.jiang@intel.com on Wed, Jun 16, 2021, 1:41 AM PDT

I am not sure if we are going to put all command that use a buffer (and finally submit to a queue) into this test, or such validation should be done in every commands' test. The queue commands themselves should be surely tested in this, but what bout others?
The same question for dawn:906

Comment 5 by cwallez@chromium.org on Wed, Jun 16, 2021, 4:27 AM PDT

I think the initial idea was that this test would test all the direct and indirect queue commands for what happens when a buffer is destroyed. That includes things like buffers in bindgroups used in a render bundle that's used in a submit. I have concerns with this approach because it means that every time we add a command to WebGPU, we need to remember to add a test in destroyed,buffer same_device,buffer, etc. Which is very error prone.

Kai instead, what do you think of having these tests in the validation tests of the respective commands instead? It would make it easier to make sure the matrix of tests is complete, and destroyed/invalid/samedevice tests could use the same helpers as the validation tests for the command.

Comment 6 by kainino@chromium.org on Wed, Jun 16, 2021, 2:36 PM PDT Project Member

My intent was that whoever starts looking at these tests would decide whether to do that or not. It's explicitly called out:

TODO: implement. (Search for other places some of these cases may have already been tested.)
Consider whether these tests should be distributed throughout the suite, instead of centralized.

Thinking about this further, I think we should indeed distribute this throughout the CTS.

We already have some places in the CTS where we test destroyed resources, like by parameterizing over {valid, invalid, destroyed} (see ValidationTest.createBufferWithState/createTextureWithState). Note that in those cases, it adds complexity, because checks for invalid are not in the same places as checks for destroyed (e.g. you can createBindGroup with a destroyed resource, but not with an invalid resource).

I think probably it's best to decide on a case-by-case basis whether to write one test parameterized over {valid, invalid, destroyed} vs writing two tests parameterized over {valid, invalid} and {valid, destroyed}. Because this should be case-by-case, having the separate subdirectory for destroyed tests doesn't make sense.

The first task to do here is go through the API and identify all of the entry points that should be checking [[destroyed]]. There are not actually that many entry points so this should be doable (command encoding functions are all irrelevant) We have some spec text for these, but it is almost certainly incomplete, and likely wrong in some places as well.
Generally: [[destroyed]] should be checked in all queue operations and mapAsync, but not checked in any object creation functions (createBindGroup, createView, finish).

Next, since this task is no longer confined to a single subdirectory, we should review all of the tests which currently call any of the destroy() functions. There aren't too many and they're mostly simple tests. We can do this incrementally, e.g. all buffer.destroy (23 instances in 12 files), then all texture.destroy (10 results in 6 files), then all queryset.destroy (4 results in 3 files) - VSCode can find these instances separately with "Find All References".

For instance, I just looked at the createView tests, which are incorrect: it_is_invalid_to_use_a_texture_view_created_from_a_destroyed_texture (which was written a long time ago) says that a destroyed texture causes an error in GPUCommandEncoder.finish, but it should not. That file is marked as needing review anyway.

Comment 7 by cwallez@chromium.org on Thu, Jun 17, 2021, 10:05 AM PDT

+1 on everything

> (command encoding functions are all irrelevant)

Do you mean that we don't need to test them? We should, unless we bundle the destroyed / mapped tests with the usage validation tests.

Comment 8 by kainino@chromium.org on Thu, Jun 17, 2021, 5:08 PM PDT

Ah, true, I guess we do need to test each of the commands with destroyed objects to make sure all of them correctly make the ~finish()~ submit() call fail. I forgot about that.

**Comment by jzm-intel** [comment]
This issue is done as the corresponding PR #1127 is landed.
The destroyed buffer related test are as below:
* writeBuffer: api,validation,queue,writeBuffer:buffer_state:*
* copyB2T, copyT2B: api,validation,image_copy,buffer_related:buffer_state:*
* copyB2B: api,validation,encoding,cmds,copyBufferToBuffer:buffer_state:*
* clearBuffer: api,validation,encoding,cmds,clearBuffer:buffer_state:*
* resolveQuerySet: api,validation,encoding,queries,resolveQuerySet:queryset_and_destination_buffer_state:*
* setIndexBuffer: api,validation,encoding,cmds,render,setIndexBuffer:index_buffer_state:*
* setVertexBuffer: api,validation,encoding,cmds,render,setVertexBuffer:vertex_buffer_state:*
* setBindGroup: api,validation,encoding,cmds,setBindGroup:state_and_binding_index:*
* draw{Index}Indirect: api,validation,encoding,cmds,render,indirect_draw:indirect_buffer_state:*
* dispatchIndirect: api,validation,encoding,cmds,compute_pass:indirect_dispatch_buffer_state:*

**Comment by Kangz** [comment]
Amazing, thanks for pushing this!
