### ISSUE TITLE
val: state,device_lost

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#882]
Tests of behavior while the device is lost.

It's probably ideal to try to test this thoroughly (for full coverage across the whole API surface), but it's a big surface. We need at least basic tests.

May want to distribute this across the test suite like device_mismatch. It's also possible these can be folded together with some other tests (like the device_mismatched, destroyed object, or other tests).

**Comment by lokokung** [comment]
Can probably close this now since tests have since been added for operations after the device is lost.
