### ISSUE TITLE
val: createBindGroup

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#884]

**Comment by kainino0x** [comment]
One known TODO: test compatibility between binding and BGL's sampleType ("unfilterable-float" etc)

**Comment by Gyuyoung** [comment]
I would like to take this issue to add missing validation tests.

**Comment by Gyuyoung** [comment]
It looks like there is no covered validation check in createBindGroup. If there is missing validation tests for createBindGroup, let me reopen this issue.
