### ISSUE TITLE
val: createBindGroupLayout

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#885]
Mostly done in 
https://github.com/gpuweb/cts/pull/719

**Comment by kainino0x** [comment]
@Gyuyoung assigning you and marking the status as "started". Please do this when you start an issue so that other contributors can see that the issue is taken. (We have at least one more person working on CTS right now, so it's a bit more important than before.)

**Comment by Gyuyoung** [comment]
@kainino0x Ah, I'm sorry for missing it. Let me keep it in mind. Thanks for assigning this issue to me.

**Comment by Gyuyoung** [comment]
I couldn't find untested validation check for createBindGroupLayout now. So, I would like to mark this issue from `Started` to `Complete`. If there is untested validation check, let me reopen this issue.
