### ISSUE TITLE
val: capability_checks,features,texture_formats for GPUTextureViewDescriptor and GPUCanvasConfiguration

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#902]
- [x] `createView` takes a `format` for the texture view, which I don't think has many tests yet (should check).
If a format from a non-enabled feature is used, it should throw an exception, just like all other places where GPUTexture is passed into the API.
- [x] GPUCanvasConfiguration also has a very limited set of formats allowed *in the device timeline validation* but also should throw an exception when *any* non-enabled texture format is used.

**Comment by kainino0x** [comment]
> In the spec, createTextureView doesn't actually allow the `format` to change, but the dictionary member is there, and it should throw an exception when unenabled features are used.

This issue summary is a little outdated, I'll fix it. createView (used to be called createTextureView) now does allow the format to change, as described here: https://gpuweb.github.io/gpuweb/#dom-gputexture-createview
> descriptor.format must be equal to either this.format or one of the formats in this.[[viewFormats]].

The core coverage needed here still hasn't changed though.

Also FYI, issue #919 is related, but not overlapping.

**Comment by Gyuyoung** [comment]
I think this issue was done by my PRs. So I would like to close this issue. But, please correct me if there is still any remaining task.

**Comment by kainino0x** [comment]
Changed status to "Complete". :)
