### ISSUE TITLE
val: Resource usage validation for textures/buffers

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#905]
webgpu:api,validation,resource_usages,buffer,*
webgpu:api,validation,resource_usages,texture,in_render_common:*
webgpu:api,validation,resource_usages,texture,in_render_misc:*

I'm not entirely clear on how much work there is here. I had it down for 12+5+5 days, but it's likely we don't need to go into as much detail as I was imagining....

**Comment by kainino0x** [comment]
@Jiawei-Shao tentatively assigning this to you if you're able to take it this sprint - sorry it looks like a huge task, but let's do it incrementally.

Since it's unclear how much work is here, what we need to do review what's there, see what updates need to be made, see what coverage is missing, and plan out the tests for buffers.

I suspect the time estimate is wrong; @Richard-Yunchao already worked on this and I think the original time estimate included all the work he already did (but I don't remember anymore, it was a long time ago).

**Comment by Jiawei-Shao** [comment]
@kainino0x  Got it.
