### ISSUE TITLE
val: cmds,render,draw vertex access tests

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#906]
Reported by kainino@chromium.org on Fri, Jun 4, 2021, 8:17 PM PDT 

There are two big draft plans here, and they need to be reviewed. I am also not even sure what the validation rules _are_ for vertex access, or whether we have finished speccing them.

See also https://crbug.com/dawn/804

Comment 14 by kainino@chromium.org on Wed, Dec 29, 2021, 6:08 PM PST

vertex_access was split up in https://github.com/gpuweb/cts/pull/698
so this issue really tracks webgpu:api,validation,encoding,cmds,render,draw:*

It also added some tests in webgpu:api,validation,encoding,cmds,render,state_tracking:*
Those can be tracked by issue dawn:862 (https://github.com/gpuweb/cts/issues/880).

And webgpu:api,operation,rendering,draw:largeish_buffer:* is tracked only in the CTS for now.

Comment 15 by kainino@chromium.org on Wed, Dec 29, 2021, 6:59 PM PST

https://github.com/gpuweb/cts/pull/851 also made progress on this task

**Comment by kainino0x** [comment]
@jzm-intel this issue was assigned to you on https://crbug.com/dawn/909 so I'm carrying it forward into sprint 100. Looks like there's still a lot to do in the CTS test descriptions so we should try to break it down and see exactly what needs to be done.

We might also need to check that we don't have duplication of these tests. I know we did some operation tests for vertex access ("correctness" tests) but not sure about validation.

**Comment by jzm-intel** [comment]
As the PRs above landed, I think this issue can be considered done.

**Comment by kainino0x** [comment]
Thanks, if so please close this issue and mark it Completed! If there are any new smaller TODOs in this part of the CTS (like to enhance coverage or something) you can filing them as issues, or draft issues, in the project, if useful.
