### ISSUE TITLE
val: device_mismatch throughout CTS

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#912]

**Comment by kainino0x** [comment]
Reopening this issue which was accidentally auto-closed by a commit (hence why it still has status "Open"). @Gyuyoung added some more of these tests recently, so they may be done now, but we still need to review and make sure.

**Comment by Gyuyoung** [comment]
Let me check if there are more tests that the `device_mismatch` validation tests need

**Comment by Gyuyoung** [comment]
It's likely we've handled most of `device_mismatch` validation. It's difficult to find missing cases.
