### ISSUE TITLE
web_platform: copyExternalImageToTexture with more formats, extended-srgb and other color spaces

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#913]
https://crbug.com/dawn/1138 adds new formats to copyExternalImageToTexture.

Some of the new formats are float, which means they go outside [0,1]. Color conversion behavior is now specified (colorspaces like srgb are extended). Find a way to test that no clamping occurs for float formats, e.g. upload a Display P3 source image - if possible.

---

Here's the single minimal test we would need in order to make sure we're implementing this correctly. It's quite simple. This is what we need to start implementing with some confidence.

- Create a Display P3 (1,0,0,1) image source. This is a red that's outside the srgb range.
  It probably has to be a PNG because it's going to have the best browser compatibility and least room for extra bugs.
- Use copyExternalImageToTexture to put it in an r(gba)16float or r(gba)32float texture with the default options.
- Test that the red channel of that texture is > 1.

Here are some test images. I took the WebKit test image and cropped it to 1x1 in GIMP.
Source: https://webkit.org/blog-files/color-gamut/

- red1x1-displayp3.png: https://webkit.org/blog-files/color-gamut/Webkit-logo-P3.png cropped to 1x1 and saved with the same color profile.
- red1x1-untagged.png: https://webkit.org/blog-files/color-gamut/Webkit-logo-P3.png cropped to 1x1 and saved with no color profile.
- red1x1-srgb.png: https://webkit.org/blog-files/color-gamut/Webkit-logo-sRGB.png cropped to 1x1 and saved with the same color profile.

Verified they display as expected on my MacBook (displayp3 is brighter than the other two).

We can test all three of these. The displayp3 red should be > 1, the others should be == 1.

Some test files are here: https://bugs.chromium.org/p/dawn/issues/detail?id=1139#c8

**Comment by shaoboyan** [comment]
This issue is fixed by above PRs

**Comment by kainino0x** [comment]
Thanks for the work on this! When closing an issue, if verifying it's complete please change the status in the project tracker to "Complete" (you can do this in the right-hand sidebar on the github issue).

Though, I noticed we never actually added any test image files to the CTS, so I guess we are only testing 2d canvas sources. I think we still need to expand these to more sources (image files, and [ImageData with colorSpace](https://developer.mozilla.org/en-US/docs/Web/API/ImageData/ImageData)), so I filed #1476 for that.
