### ISSUE TITLE
val: capability_checks,features errors should be exceptions

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#919]
Need to update query_types tests

**Comment by kainino0x** [comment]
Fixed by https://github.com/gpuweb/cts/pull/1499

**Comment by kainino0x** [comment]
Wait, no, #1499 only fixed the texture cases. Seems like there may also be fixes needed in other places.

**Comment by jchen10** [comment]
@kainino0x I am working on the optimization of 0-copy video import on ChromeOS. It's unfortunately no better than WebGL yet. I may still need a couple of weeks on that. If this task is urgent, please assign it to someone else. Otherwise I would take case of it as soon as I've done my current work.

**Comment by kainino0x** [comment]
No worries, this isn't urgent. I just was looking at it because Brandon was fixing some of these.

@toji if you *happen* to want to take the rest of these then you would be welcome to.

**Comment by kainino0x** [comment]
Assigning @Gyuyoung who started working on this.

#1571 fixes the existing test for createQuerySet, but it looks like we are still missing a test for writeTimestamp, which should also throw a TypeError when the feature is not enabled.

**Comment by Gyuyoung** [comment]
@kainino0x I added the test to check if writeTimestamp test throws an exception in #1584. So, I would like to mark this task as `completed`. If we have more tasks to complete, please let me know.

**Comment by kainino0x** [comment]
I don't recall for sure, but according to my last comment it sounds like it's complete!
