### ISSUE TITLE
val: capability_checks,features,texture_formats for GPUTextureDescriptor.viewFormats

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#920]

**Comment by kainino0x** [comment]
LGTM! The only other thing is please change the status in the project from "Blocked" to "Complete" (this got unblocked when we finished the spec change and should have been changed to "Open" at that time).

This is redundant with closing the issue, but we change the status manually because sometimes we accidentally [auto-close an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) with a PR when the issue is not completed yet.

**Comment by kainino0x** [comment]
You can change the status either from the project page or simply from the sidebar on this github issue.

**Comment by Gyuyoung** [comment]
ok, I change the status to "Complete"!
