### ISSUE TITLE
val: mapAsync,state,destroyed

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#929]
just like unmap(), destroy() should be valid, but the map promise should AbortError.

not sure where to put this, see validation,buffer,destroy and validation,buffer,mapping both of which nearly test this. Maybe just update both, no harm in duplicate coverage.

**Comment by kainino0x** [comment]
Retriaging as "Blocked" because https://github.com/gpuweb/gpuweb/issues/2545

**Comment by kainino0x** [comment]
This isn't blocked anymore. I'm not sure whether it's tested, but whoever takes this can check.

**Comment by lokokung** [comment]
Renaming this issue (and assigning to myself for now). I think it makes most sense to add this under val:buffer,mapping since the val:buffer,destroy one isn't really actively testing for errors. I'll clean both of them up when I implement this.

**Comment by lokokung** [comment]
PR above fixes the issue, so closing.
