### ISSUE TITLE
val: beginRenderPass resolveTarget format must support resolve

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#940]
see the "resolve" column in the format table

**Comment by kainino0x** [comment]
While looking at this, should also ensure `webgpu:api,validation,createTexture:sampleCount,various_sampleCount_with_all_formats:*` is up to date with the table in the spec

**Comment by Jiawei-Shao** [comment]
I find we need a decision on whether we support multisampling on non-renderable formats before I can start implementing and fixing these tests.

**Comment by kainino0x** [comment]
@Jiawei-Shao the spec issue is resolved on https://github.com/gpuweb/gpuweb/issues/2465, it's just that the spec text hasn't been updated yet. So we can go ahead and update the tests to follow the decision.
