### ISSUE TITLE
reftest: rendering via transferControlToOffscreen

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#941]

**Comment by kainino0x** [comment]
cc @Juanmihd from https://crbug.com/1202676

**Comment by greggman** [comment]
does this need to go through a worker or is it fine in the main thread?

In other words, does the test need to be 

1. create canvas
2. transfer to offscreen
3. postMessage offscren to worker
4. in worker offscreen.getContext('webgpu') and render to it

Or can it just be

1. create canvas
2. transfer to offscreen
3. offscren.getContext('webgpu') and render to it

**Comment by kainino0x** [comment]
I think we should have ones that go through a worker, to catch odd issues like the compositing not getting invalidated after draws. I think you already added them though?

**Comment by greggman** [comment]
yea, I added them.
