### ISSUE TITLE
Add comprehensive memory model tests

### ISSUE THREAD

**Issue by reeselevine** [gpuweb/cts#963]
We've been working on new strategies for testing GPU memory models at UC Santa Cruz, and as part of that we've been looking at WebGPU and its memory model. At this point, we feel like we have developed a strong testing strategy that will create more confidence in WebGPU implementations. 

We've built a website for exploring different memory model tests at https://gpuharbor.ucsc.edu/webgpu-mem-testing/. The goal here would be to add some or all of the tests at https://gpuharbor.ucsc.edu/webgpu-mem-testing/conformance/ to this conformance test suite.

For some more background and some detail on our actual tests, here's the slides from a presentation I gave to the WebGPU working group in mid-December: https://docs.google.com/presentation/d/1Gr8zbiE8yfBaijAqniv_rJbvs_mJzKapvfBoHkTZNjQ/edit?usp=sharing.

I'll plan on opening a PR with an initial test plan, and iterate from there!

@tyler-utah @dneto0 @alan-baker

**Comment by dneto0** [comment]
I think that's the last of the bunch that were originally planned?  Should we close this?

**Comment by reeselevine** [comment]
Yep, that was all of them, I'll close it now!
