### ISSUE TITLE
val: unimplemented createRenderPipeline and createRenderPipelineAsync validation tests

### ISSUE THREAD

**Issue by Jiawei-Shao** [gpuweb/cts#982]
Below two tests in `createRenderPipeline` and `createRenderPipelineAsync` validation tests are unimplemented:
- pipeline_output_targets,format_blendable
- pipeline_output_targets,blend_min_max

**Comment by kainino0x** [comment]
This issue was duplicated 2 "draft" issues in the project, so I deleted those.
(Those could have been converted to issues instead, or merged and then converted to an issue: https://github.com/gpuweb/cts/blob/main/docs/intro/developing.md#pull-requests)
